#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import re
import subprocess
import sys
from pathlib import Path


BUILD_IN_DIR = Path(__file__).resolve().parent
TOOLS_DIR = BUILD_IN_DIR.parent
ROOT_DIR = BUILD_IN_DIR.parents[2]
CONFIG_PATH = BUILD_IN_DIR / "material_symbols_common_icons.json"
TEXT_PATH = BUILD_IN_DIR / "material_symbols_common_text.txt"
RESOURCE_DIR = ROOT_DIR / "src" / "resource"
TTF2C_PATH = TOOLS_DIR / "ttf2c.py"


def load_config():
    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        return json.load(file)


def utf8_escape(codepoint):
    return "".join(f"\\x{byte:02X}" for byte in chr(codepoint).encode("utf-8"))


def icon_macro_name(name):
    return "".join(ch if ch.isalnum() else "_" for ch in name.upper())


def unique_icon_items(icon_items):
    seen_codepoints = set()
    ordered_items = []
    for item in icon_items:
        codepoint = item["codepoint"].upper()
        if codepoint in seen_codepoints:
            continue
        seen_codepoints.add(codepoint)
        ordered_items.append({"name": item["name"], "codepoint": codepoint})
    return ordered_items


def build_icon_lookup(icon_items):
    return {chr(int(item["codepoint"], 16)): item for item in unique_icon_items(icon_items)}


def format_icon_comment(item):
    return f'icon "{item["name"]}" U+{item["codepoint"]}'


def rewrite_generated_source_comments(source_path, icon_items):
    icon_lookup = build_icon_lookup(icon_items)
    text = source_path.read_text(encoding="utf-8")

    support_lines = [" * Total character count: {0} Supported icons:".format(len(icon_lookup))]
    for item in icon_lookup.values():
        support_lines.append(f' * - {item["name"]} (U+{item["codepoint"]})')
    support_block = "/**\n" + "\n".join(support_lines) + "\n */\n"
    text = re.sub(r"/\*\*\n \* Total character count: .*?\n \*/\n", support_block, text, count=1, flags=re.S)

    def replace_glyph_comment(match):
        char = match.group("char")
        utf8_value = match.group("utf8")
        item = icon_lookup.get(char)
        if item is None:
            return match.group(0)
        return f'    /* Glyph for {format_icon_comment(item)} {utf8_value} */'

    def replace_char_desc_comment(match):
        prefix = match.group("prefix")
        char = match.group("char")
        utf8_value = match.group("utf8")
        item = icon_lookup.get(char)
        if item is None:
            return match.group(0)
        return f'{prefix}/* {format_icon_comment(item)} {utf8_value} */'

    text = re.sub(
        r'    /\* Glyph for character "(?P<char>.)" (?P<utf8>0x[0-9a-fA-F]+) \*/',
        replace_glyph_comment,
        text,
    )
    text = re.sub(
        r'(?P<prefix>\}, )/\* "(?P<char>.)" (?P<utf8>0x[0-9a-fA-F]+) \*/',
        replace_char_desc_comment,
        text,
    )

    source_path.write_text(text, encoding="utf-8", newline="\n")


def build_var_coords(config, size):
    raw = config["variation_coords"]
    values = []
    for key in ("fill", "grad", "opsz", "wght"):
        value = raw[key]
        if value == "size":
            value = size
        values.append(str(value))
    return ",".join(values)


def write_text_file(icon_items):
    seen_codepoints = set()
    with TEXT_PATH.open("w", encoding="utf-8", newline="\n") as file:
        for item in icon_items:
            codepoint = item["codepoint"].upper()
            if codepoint in seen_codepoints:
                continue
            seen_codepoints.add(codepoint)
            file.write(f"&#x{codepoint};\n")


def render_header(config, icon_items):
    font_name = config["font_name"]
    header_name = config["header_file"]
    header_guard = "_" + Path(header_name).stem.upper() + "_H_"
    lines = [
        f"#ifndef {header_guard}",
        f"#define {header_guard}",
        "",
        '#include "font/egui_font_std.h"',
        "",
        "/* Set up for C function definitions, even when using C++ */",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "/* Auto-generated by scripts/tools/build_in/built_in_icon_font_gen.py. */",
        "",
    ]

    for size in config["sizes"]:
        lines.append(f"extern const egui_font_std_t egui_res_font_{font_name}_{size}_{config['font_bit_size']};")

    lines.extend([""])

    for size in config["sizes"]:
        lines.append(f"#define EGUI_FONT_ICON_MS_{size} ((const egui_font_t *)&egui_res_font_{font_name}_{size}_{config['font_bit_size']})")

    lines.extend([""])

    for item in icon_items:
        codepoint = int(item["codepoint"], 16)
        macro = icon_macro_name(item["name"])
        lines.append(f"#define EGUI_ICON_MS_{macro}_CODEPOINT 0x{codepoint:04X}u")
        lines.append(f'#define EGUI_ICON_MS_{macro} "{utf8_escape(codepoint)}"')

    lines.extend(
        [
            "",
            "/* Ends C function definitions when using C++ */",
            "#ifdef __cplusplus",
            "}",
            "#endif",
            "",
            f"#endif /* {header_guard} */",
            "",
        ]
    )

    header_path = RESOURCE_DIR / header_name
    with header_path.open("w", encoding="utf-8", newline="\n") as file:
        file.write("\n".join(lines))


def generate_fonts(config):
    icon_items = config["icons"]
    for size in config["sizes"]:
        var_coords = build_var_coords(config, size)
        print(f"Generating Material Symbols common {size}px")
        output_path = RESOURCE_DIR / f"egui_res_font_{config['font_name']}_{size}_{config['font_bit_size']}.c"
        subprocess.run(
            [
                sys.executable,
                str(TTF2C_PATH),
                "-i",
                config["font_file"],
                "-n",
                config["font_name"],
                "-t",
                TEXT_PATH.name,
                "-p",
                str(size),
                "-s",
                str(config["font_bit_size"]),
                "-o",
                str(RESOURCE_DIR),
                "--var-coords",
                var_coords,
            ],
            cwd=BUILD_IN_DIR,
            check=True,
        )
        rewrite_generated_source_comments(output_path, icon_items)


def main():
    config = load_config()
    icon_items = config["icons"]

    write_text_file(icon_items)
    render_header(config, icon_items)
    generate_fonts(config)


if __name__ == "__main__":
    main()
