

#ifndef _APP_EGUI_RESOURCE_GENERATE_H_
#define _APP_EGUI_RESOURCE_GENERATE_H_

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

#include "egui.h"

extern const egui_image_qoi_t egui_res_image_star_120_ext_qoi_rgb565_8_bin;
extern const egui_image_std_t egui_res_image_star_120_ext_rgb565_1_bin;
extern const egui_image_std_t egui_res_image_star_120_ext_rgb565_2_bin;
extern const egui_image_std_t egui_res_image_star_120_ext_rgb565_4_bin;
extern const egui_image_std_t egui_res_image_star_120_ext_rgb565_8_bin;
extern const egui_image_rle_t egui_res_image_star_120_ext_rle_rgb565_8_bin;
extern const egui_image_qoi_t egui_res_image_star_120_qoi_rgb565_8;
extern const egui_image_std_t egui_res_image_star_120_rgb565_1;
extern const egui_image_std_t egui_res_image_star_120_rgb565_2;
extern const egui_image_std_t egui_res_image_star_120_rgb565_4;
extern const egui_image_std_t egui_res_image_star_120_rgb565_8;
extern const egui_image_rle_t egui_res_image_star_120_rle_rgb565_8;
extern const egui_image_qoi_t egui_res_image_star_240_ext_qoi_rgb565_8_bin;
extern const egui_image_std_t egui_res_image_star_240_ext_rgb565_1_bin;
extern const egui_image_std_t egui_res_image_star_240_ext_rgb565_2_bin;
extern const egui_image_std_t egui_res_image_star_240_ext_rgb565_4_bin;
extern const egui_image_std_t egui_res_image_star_240_ext_rgb565_8_bin;
extern const egui_image_rle_t egui_res_image_star_240_ext_rle_rgb565_8_bin;
extern const egui_image_qoi_t egui_res_image_star_240_qoi_rgb565_8;
extern const egui_image_std_t egui_res_image_star_240_rgb565_1;
extern const egui_image_std_t egui_res_image_star_240_rgb565_2;
extern const egui_image_std_t egui_res_image_star_240_rgb565_4;
extern const egui_image_std_t egui_res_image_star_240_rgb565_8;
extern const egui_image_rle_t egui_res_image_star_240_rle_rgb565_8;
extern const egui_image_std_t egui_res_image_star_40_ext_rgb565_1_bin;
extern const egui_image_std_t egui_res_image_star_40_ext_rgb565_2_bin;
extern const egui_image_std_t egui_res_image_star_40_ext_rgb565_4_bin;
extern const egui_image_std_t egui_res_image_star_40_ext_rgb565_8_bin;
extern const egui_image_qoi_t egui_res_image_star_40_qoi_rgb565_8;
extern const egui_image_std_t egui_res_image_star_40_rgb565_1;
extern const egui_image_std_t egui_res_image_star_40_rgb565_2;
extern const egui_image_std_t egui_res_image_star_40_rgb565_4;
extern const egui_image_std_t egui_res_image_star_40_rgb565_8;
extern const egui_image_rle_t egui_res_image_star_40_rle_rgb565_8;
extern const egui_image_std_t egui_res_image_star_pure_120_alpha_8;
extern const egui_image_std_t egui_res_image_star_pure_240_alpha_8;
extern const egui_image_qoi_t egui_res_image_test_perf_120_ext_qoi_rgb565_0_bin;
extern const egui_image_std_t egui_res_image_test_perf_120_ext_rgb565_0_bin;
extern const egui_image_rle_t egui_res_image_test_perf_120_ext_rle_rgb565_0_bin;
extern const egui_image_qoi_t egui_res_image_test_perf_120_qoi_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_120_rgb565_0;
extern const egui_image_rle_t egui_res_image_test_perf_120_rle_rgb565_0;
extern const egui_image_qoi_t egui_res_image_test_perf_240_ext_qoi_rgb565_0_bin;
extern const egui_image_std_t egui_res_image_test_perf_240_ext_rgb565_0_bin;
extern const egui_image_rle_t egui_res_image_test_perf_240_ext_rle_rgb565_0_bin;
extern const egui_image_qoi_t egui_res_image_test_perf_240_qoi_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_240_rgb565_0;
extern const egui_image_rle_t egui_res_image_test_perf_240_rle_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_40_ext_rgb565_0_bin;
extern const egui_image_qoi_t egui_res_image_test_perf_40_qoi_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_40_rgb565_0;
extern const egui_image_rle_t egui_res_image_test_perf_40_rle_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_480_rgb565_0;
extern const egui_font_std_t egui_res_font_montserrat_perf_26_4_bin;


enum {
EGUI_EXT_RES_ID_BASE = 0x00, // avoid conflict with NULL.
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_QOI_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_1_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_1_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_2_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_2_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_4_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_4_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RLE_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_120_EXT_RLE_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_QOI_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_1_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_1_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_2_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_2_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_4_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_4_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RLE_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_240_EXT_RLE_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_1_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_1_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_2_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_2_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_4_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_4_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_STAR_40_EXT_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_120_EXT_QOI_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_120_EXT_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_120_EXT_RLE_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_QOI_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_RLE_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_40_EXT_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_FONT_MONTSERRAT_PERF_26_4_PIXEL_BUFFER,
EGUI_EXT_RES_ID_EGUI_RES_FONT_MONTSERRAT_PERF_26_4_CHAR_DESC,

EGUI_EXT_RES_ID_MAX,
};

extern const uint32_t egui_ext_res_id_map[EGUI_EXT_RES_ID_MAX];

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_RESOURCE_GENERATE_H_ */

