#ifndef _EGUI_I18N_H_
#define _EGUI_I18N_H_

/**
 * @file egui_i18n.h
 * @brief Internationalization (i18n) string resource API for EmbeddedGUI.
 *
 * This module provides multi-language string support using a simple
 * table-based approach. String tables are generated by the Designer tool
 * from Android-style values/strings.xml resource files.
 *
 * Usage:
 *   1) Include the generated "egui_strings.h" in your app.
 *   2) At startup, optionally call egui_i18n_set_locale() to choose a locale.
 *   3) Use egui_i18n_get(string_id) to retrieve the localized string.
 *
 * The generated code provides:
 *   - An enum of string IDs (EGUI_STR_xxx)
 *   - One string table per locale
 *   - Registration of locale tables
 */

#include <stdint.h>

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief A locale string table: array of C strings indexed by string_id.
 */
typedef struct egui_i18n_locale
{
    const char *locale_code;    /**< Locale identifier, e.g. "en", "zh", "" for default */
    const char **strings;       /**< Array of string pointers, indexed by string_id */
    uint16_t count;             /**< Number of strings in the table */
} egui_i18n_locale_t;

/**
 * @brief Initialize the i18n system with an array of locale tables.
 *
 * Typically called once at startup from the generated egui_strings init code.
 *
 * @param locales       Array of locale table pointers.
 * @param locale_count  Number of locales in the array.
 */
void egui_i18n_init(const egui_i18n_locale_t *locales, uint16_t locale_count);

/**
 * @brief Set the active locale by index.
 *
 * @param locale_index  Index into the locales array (0 = default).
 */
void egui_i18n_set_locale(uint16_t locale_index);

/**
 * @brief Set the active locale by locale code string.
 *
 * Searches for a matching locale code. If not found, falls back to index 0.
 *
 * @param locale_code   Locale identifier string (e.g., "zh", "ja").
 */
void egui_i18n_set_locale_by_code(const char *locale_code);

/**
 * @brief Get the current locale index.
 *
 * @return Current locale index.
 */
uint16_t egui_i18n_get_locale(void);

/**
 * @brief Get a localized string by its ID.
 *
 * If the string is not available in the current locale, falls back to the
 * default locale (index 0). If still not found, returns an empty string.
 *
 * @param string_id     The string resource ID (from generated enum).
 * @return Pointer to the localized string (never NULL).
 */
const char *egui_i18n_get(uint16_t string_id);

/**
 * @brief Get the number of registered locales.
 *
 * @return Number of locales.
 */
uint16_t egui_i18n_get_locale_count(void);

/**
 * @brief Get the locale code for a given locale index.
 *
 * @param locale_index  Index into the locales array.
 * @return Locale code string, or "" if index is out of range.
 */
const char *egui_i18n_get_locale_code(uint16_t locale_index);

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _EGUI_I18N_H_ */
