

#ifndef _APP_EGUI_RESOURCE_GENERATE_H_
#define _APP_EGUI_RESOURCE_GENERATE_H_

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

#include "egui.h"

extern const egui_image_std_t egui_res_image_star_240_rgb565_0;
extern const egui_image_std_t egui_res_image_star_240_rgb565_1;
extern const egui_image_std_t egui_res_image_star_240_rgb565_2;
extern const egui_image_std_t egui_res_image_star_240_rgb565_4;
extern const egui_image_std_t egui_res_image_star_240_rgb565_8;
extern const egui_image_std_t egui_res_image_star_40_rgb565_0;
extern const egui_image_std_t egui_res_image_star_40_rgb565_1;
extern const egui_image_std_t egui_res_image_star_40_rgb565_2;
extern const egui_image_std_t egui_res_image_star_40_rgb565_4;
extern const egui_image_std_t egui_res_image_star_40_rgb565_8;
extern const egui_image_std_t egui_res_image_star_rgb565_8;
extern const egui_image_std_t egui_res_image_test_perf_240_ext_a1_rgb565_1_bin;
extern const egui_image_std_t egui_res_image_test_perf_240_ext_a2_rgb565_2_bin;
extern const egui_image_std_t egui_res_image_test_perf_240_ext_a4_rgb565_4_bin;
extern const egui_image_std_t egui_res_image_test_perf_240_ext_a8_rgb565_8_bin;
extern const egui_image_std_t egui_res_image_test_perf_240_ext_rgb565_0_bin;
extern const egui_image_std_t egui_res_image_test_perf_240_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_240_rgb565_1;
extern const egui_image_std_t egui_res_image_test_perf_240_rgb565_2;
extern const egui_image_std_t egui_res_image_test_perf_240_rgb565_4;
extern const egui_image_std_t egui_res_image_test_perf_240_rgb565_8;
extern const egui_image_std_t egui_res_image_test_perf_40_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_40_rgb565_1;
extern const egui_image_std_t egui_res_image_test_perf_40_rgb565_2;
extern const egui_image_std_t egui_res_image_test_perf_40_rgb565_4;
extern const egui_image_std_t egui_res_image_test_perf_40_rgb565_8;
extern const egui_image_std_t egui_res_image_test_perf_480_ext_a1_rgb565_1_bin;
extern const egui_image_std_t egui_res_image_test_perf_480_ext_a2_rgb565_2_bin;
extern const egui_image_std_t egui_res_image_test_perf_480_ext_a4_rgb565_4_bin;
extern const egui_image_std_t egui_res_image_test_perf_480_ext_a8_rgb565_8_bin;
extern const egui_image_std_t egui_res_image_test_perf_480_ext_rgb565_0_bin;
extern const egui_image_std_t egui_res_image_test_perf_480_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_480_rgb565_1;
extern const egui_image_std_t egui_res_image_test_perf_480_rgb565_2;
extern const egui_image_std_t egui_res_image_test_perf_480_rgb565_4;
extern const egui_image_std_t egui_res_image_test_perf_480_rgb565_8;
extern const egui_image_std_t egui_res_image_test_perf_960_rgb565_0;
extern const egui_image_std_t egui_res_image_test_perf_960_rgb565_1;
extern const egui_image_std_t egui_res_image_test_perf_960_rgb565_2;
extern const egui_image_std_t egui_res_image_test_perf_960_rgb565_4;
extern const egui_image_std_t egui_res_image_test_perf_960_rgb565_8;
extern const egui_image_std_t egui_res_image_test_rgb565_8;
extern const egui_font_std_t egui_res_font_montserrat_perf_26_4_bin;


enum {
EGUI_EXT_RES_ID_BASE = 0x00, // avoid conflict with NULL.
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A1_RGB565_1_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A1_RGB565_1_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A2_RGB565_2_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A2_RGB565_2_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A4_RGB565_4_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A4_RGB565_4_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A8_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_A8_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_240_EXT_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A1_RGB565_1_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A1_RGB565_1_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A2_RGB565_2_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A2_RGB565_2_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A4_RGB565_4_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A4_RGB565_4_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A8_RGB565_8_ALPHA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_A8_RGB565_8_DATA,
EGUI_EXT_RES_ID_EGUI_RES_IMAGE_TEST_PERF_480_EXT_RGB565_0_DATA,
EGUI_EXT_RES_ID_EGUI_RES_FONT_MONTSERRAT_PERF_26_4_PIXEL_BUFFER,
EGUI_EXT_RES_ID_EGUI_RES_FONT_MONTSERRAT_PERF_26_4_CHAR_DESC,

EGUI_EXT_RES_ID_MAX,
};

extern const uint32_t egui_ext_res_id_map[EGUI_EXT_RES_ID_MAX];

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_RESOURCE_GENERATE_H_ */

