#ifndef _APP_EGUI_CONFIG_H_
#define _APP_EGUI_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define EGUI_CONFIG_FUNCTION_SUPPORT_MASK         0
#define EGUI_CONFIG_FUNCTION_IMAGE_CODEC_QOI      0
#define EGUI_CONFIG_FUNCTION_IMAGE_CODEC_RLE      0
#define EGUI_CONFIG_FUNCTION_WIDGET_ENHANCED_DRAW 0
#define EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW       0
#define EGUI_CONFIG_FUNCTION_SUPPORT_LAYER        0
#define EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR    1
#define EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH        1
#define EGUI_CONFIG_FUNCTION_SUPPORT_KEY          0
#define EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS        0
#define EGUI_CONFIG_CIRCLE_DEFAULT_ALGO_HQ        0
#define EGUI_CONFIG_FUNCTION_FONT_STD_FAST_DRAW   1

#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_CONFIG_H_ */
