EGUI_CODE_SRC += $(EGUI_APP_PATH)

EGUI_CODE_INCLUDE += $(EGUI_APP_PATH)

APP_SUB ?= canvas_path_probe

EGUI_APP_SUB_PATH := $(EGUI_APP_PATH)/$(APP_SUB)

APP_OBJ_SUFFIX := HelloSizeAnalysis_$(APP_SUB)

EGUI_CODE_SRC += $(EGUI_APP_SUB_PATH)
EGUI_CODE_SRC += $(EGUI_APP_SUB_PATH)/resource
EGUI_CODE_SRC += $(EGUI_APP_SUB_PATH)/resource/img
EGUI_CODE_SRC += $(EGUI_APP_SUB_PATH)/resource/font

EGUI_CODE_INCLUDE += $(EGUI_APP_SUB_PATH)
EGUI_CODE_INCLUDE += $(EGUI_APP_SUB_PATH)/resource

EGUI_APP_RESOURCE_PATH ?= $(EGUI_APP_SUB_PATH)/resource
