#ifndef _SIZE_ANALYSIS_PROBE_CONFIG_H_
#define _SIZE_ANALYSIS_PROBE_CONFIG_H_

#define EGUI_SIZE_PROBE_WIDGET_SLIDER 1
#define EGUI_SIZE_PROBE_WIDGET_SWITCH 1
#define EGUI_SIZE_PROBE_WIDGET_PAGE_INDICATOR 1
#define EGUI_SIZE_PROBE_WIDGET_STEPPER 1
#define EGUI_SIZE_PROBE_WIDGET_CPB 1
#define EGUI_SIZE_PROBE_WIDGET_GAUGE 1
#define EGUI_SIZE_PROBE_WIDGET_ACTIVITY_RING 1
#define EGUI_SIZE_PROBE_WIDGET_ANALOG_CLOCK 1
#define EGUI_SIZE_PROBE_WIDGET_LINE 1
#define EGUI_SIZE_PROBE_WIDGET_CHART_LINE 1

#endif /* _SIZE_ANALYSIS_PROBE_CONFIG_H_ */
