"""String resource C code generator for EmbeddedGUI Designer.

Generates C source files from the ``StringResourceCatalog`` model:

    egui_strings.h   — string ID enum + locale index enum + extern declarations
    egui_strings.c   — all locale string tables + i18n init function

These files are written to the app directory alongside other generated C files.
The generated code uses the ``egui_i18n`` runtime API from
``src/resource/egui_i18n.h``.

Example generated output
========================

egui_strings.h::

    #ifndef _EGUI_STRINGS_H_
    #define _EGUI_STRINGS_H_

    #include "resource/egui_i18n.h"

    enum {
        EGUI_STR_APP_NAME = 0,
        EGUI_STR_HELLO,
        EGUI_STR_COUNT,
    };

    enum {
        EGUI_LOCALE_DEFAULT = 0,
        EGUI_LOCALE_ZH,
        EGUI_LOCALE_COUNT,
    };

    void egui_strings_init(void);

    #endif

egui_strings.c::

    #include "egui_strings.h"

    // Default locale strings
    static const char *s_strings_default[] = {
        "My App",   // EGUI_STR_APP_NAME
        "Hello",    // EGUI_STR_HELLO
    };

    // zh locale strings
    static const char *s_strings_zh[] = {
        "我的应用",  // EGUI_STR_APP_NAME
        "你好",     // EGUI_STR_HELLO
    };

    static const egui_i18n_locale_t s_locales[] = {
        { "", s_strings_default, EGUI_STR_COUNT },
        { "zh", s_strings_zh, EGUI_STR_COUNT },
    };

    void egui_strings_init(void) {
        egui_i18n_init(s_locales, EGUI_LOCALE_COUNT);
    }
"""

from ..model.string_resource import StringResourceCatalog, DEFAULT_LOCALE


def _key_to_enum(key):
    """Convert a string key to its C enum constant name.

    ``"app_name"`` -> ``"EGUI_STR_APP_NAME"``
    """
    return f"EGUI_STR_{key.upper()}"


def _locale_to_enum(locale_code):
    """Convert a locale code to its C enum constant name.

    ``""`` -> ``"EGUI_LOCALE_DEFAULT"``
    ``"zh"`` -> ``"EGUI_LOCALE_ZH"``
    """
    if locale_code == DEFAULT_LOCALE:
        return "EGUI_LOCALE_DEFAULT"
    return f"EGUI_LOCALE_{locale_code.upper()}"


def _locale_to_array_name(locale_code):
    """Convert a locale code to the static array variable name.

    ``""`` -> ``"s_strings_default"``
    ``"zh"`` -> ``"s_strings_zh"``
    """
    if locale_code == DEFAULT_LOCALE:
        return "s_strings_default"
    return f"s_strings_{locale_code.lower()}"


def _locale_display(locale_code):
    """Human-readable locale name for comments."""
    if locale_code == DEFAULT_LOCALE:
        return "Default"
    return locale_code


def _escape_c_string(text):
    """Escape a string for use as a C string literal."""
    result = []
    for ch in text:
        if ch == '"':
            result.append('\\"')
        elif ch == '\\':
            result.append('\\\\')
        elif ch == '\n':
            result.append('\\n')
        elif ch == '\r':
            result.append('\\r')
        elif ch == '\t':
            result.append('\\t')
        else:
            result.append(ch)
    return "".join(result)


def generate_strings_header(catalog):
    """Generate ``egui_strings.h`` content.

    Args:
        catalog: StringResourceCatalog instance.

    Returns:
        str: Generated header file content.
    """
    keys = catalog.all_keys
    locales = catalog.locales

    lines = []
    lines.append("#ifndef _EGUI_STRINGS_H_")
    lines.append("#define _EGUI_STRINGS_H_")
    lines.append("")
    lines.append("// ===== Auto-generated by EmbeddedGUI Designer =====")
    lines.append("// DO NOT EDIT — this file is fully regenerated.")
    lines.append("")
    lines.append('#include "resource/egui_i18n.h"')
    lines.append("")
    lines.append("/* Set up for C function definitions, even when using C++ */")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    # String ID enum
    lines.append("// String resource IDs")
    lines.append("enum {")
    for i, key in enumerate(keys):
        suffix = " = 0," if i == 0 else ","
        lines.append(f"    {_key_to_enum(key)}{suffix}")
    lines.append("    EGUI_STR_COUNT,")
    lines.append("};")
    lines.append("")

    # Locale index enum
    lines.append("// Locale indices")
    lines.append("enum {")
    for i, locale in enumerate(locales):
        suffix = " = 0," if i == 0 else ","
        lines.append(f"    {_locale_to_enum(locale)}{suffix}")
    lines.append("    EGUI_LOCALE_COUNT,")
    lines.append("};")
    lines.append("")

    # Init function declaration
    lines.append("/**")
    lines.append(" * @brief Initialize the i18n string tables.")
    lines.append(" * Call this once at startup (e.g., in uicode_init).")
    lines.append(" */")
    lines.append("void egui_strings_init(void);")
    lines.append("")

    lines.append("/* Ends C function definitions when using C++ */")
    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* _EGUI_STRINGS_H_ */")
    lines.append("")

    return "\n".join(lines)


def generate_strings_source(catalog):
    """Generate ``egui_strings.c`` content with all locale tables.

    Args:
        catalog: StringResourceCatalog instance.

    Returns:
        str: Generated source file content.
    """
    keys = catalog.all_keys
    locales = catalog.locales

    lines = []
    lines.append("// ===== Auto-generated by EmbeddedGUI Designer =====")
    lines.append("// DO NOT EDIT — this file is fully regenerated.")
    lines.append("")
    lines.append('#include "egui_strings.h"')
    lines.append("")

    # Generate string table for each locale
    for locale in locales:
        arr_name = _locale_to_array_name(locale)
        display = _locale_display(locale)
        lines.append(f"// {display} locale strings")
        lines.append(f"static const char *{arr_name}[] = {{")
        for key in keys:
            value = catalog.get(key, locale)
            escaped = _escape_c_string(value)
            lines.append(f'    "{escaped}",  // {_key_to_enum(key)}')
        lines.append("};")
        lines.append("")

    # Generate locale table array
    lines.append("static const egui_i18n_locale_t s_locales[] = {")
    for locale in locales:
        arr_name = _locale_to_array_name(locale)
        code_str = _escape_c_string(locale)
        lines.append(f'    {{ "{code_str}", {arr_name}, EGUI_STR_COUNT }},')
    lines.append("};")
    lines.append("")

    # Init function
    lines.append("void egui_strings_init(void)")
    lines.append("{")
    lines.append("    egui_i18n_init(s_locales, EGUI_LOCALE_COUNT);")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def generate_string_files(catalog):
    """Generate all string resource C files.

    Args:
        catalog: StringResourceCatalog instance.

    Returns:
        dict[str, tuple[str, str]]: filename -> (content, category)
            Returns empty dict if catalog has no strings.
    """
    if not catalog.has_strings:
        return {}

    from ..generator.code_generator import GENERATED_ALWAYS

    files = {}
    files["egui_strings.h"] = (generate_strings_header(catalog), GENERATED_ALWAYS)
    files["egui_strings.c"] = (generate_strings_source(catalog), GENERATED_ALWAYS)

    return files
