#ifndef _SIZE_ANALYSIS_APP_CONFIG_OVERRIDE_H_
#define _SIZE_ANALYSIS_APP_CONFIG_OVERRIDE_H_

#define EGUI_CONFIG_FUNCTION_SUPPORT_MASK 0
#define EGUI_CONFIG_IMAGE_CODEC_QOI_ENABLE 1
#define EGUI_CONFIG_IMAGE_CODEC_RLE_ENABLE 0

#endif /* _SIZE_ANALYSIS_APP_CONFIG_OVERRIDE_H_ */
