#ifndef _APP_EGUI_CONFIG_H_
#define _APP_EGUI_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define EGUI_CONFIG_FUNCTION_SUPPORT_MASK          0
#define EGUI_CONFIG_IMAGE_CODEC_QOI_ENABLE         0
#define EGUI_CONFIG_IMAGE_CODEC_RLE_ENABLE         0
#define EGUI_CONFIG_WIDGET_ENHANCED_DRAW           0
#define EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW        0
#define EGUI_CONFIG_FUNCTION_SUPPORT_LAYER         0
#define EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR     0
#define EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH         0
#define EGUI_CONFIG_FUNCTION_SUPPORT_KEY           1
#define EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS         0
#define EGUI_CONFIG_CIRCLE_DEFAULT_ALGO_HQ         0
#define EGUI_CONFIG_FONT_STD_FAST_DRAW_ENABLE         0
#define EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8 0
#define EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8  0

#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_CONFIG_H_ */
