#ifndef _EGUI_VIEW_TEST_PERFORMANCE_H_
#define _EGUI_VIEW_TEST_PERFORMANCE_H_

#include "widget/egui_view.h"

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

enum
{
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_LINE = 0x0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_RECTANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_CORNERS,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_RECTANGLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_CORNERS_FILL,

    // Triangle
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL,

    // Ellipse (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_ELLIPSE)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ELLIPSE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ELLIPSE_FILL,

    // Polygon (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_POLYGON)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_POLYGON,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_POLYGON_FILL,

    // Bezier (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_BEZIER)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_BEZIER_QUAD,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_BEZIER_CUBIC,

    // HQ circle/arc (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_CIRCLE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_FILL_HQ,

    // HQ line (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_LINE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_LINE_HQ,

    // Gradient (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_GRADIENT)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_TRIANGLE,

    // Shadow (EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_SHADOW,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_SHADOW_ROUND,

    // Mask performance tests
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_ROUND_RECT_FILL_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_ROUND_RECT_FILL_WITH_MASK,

    // Animation performance tests
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_TRANSLATE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_ALPHA,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_SCALE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_SET,

    // Image multi-size tests
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8_DOUBLE,

    // Extern image performance tests
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_8,

    // Mask multi-size: rect fill
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE_DOUBLE,

    // Mask multi-size: image
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE_DOUBLE,

    // Shape fill multi-size
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL_DOUBLE,

    // Image transform (rotation + scale)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_RESIZE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_DOUBLE,

    // External image transform (rotation)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_8,

    // Star image tests (real alpha, image source: star.png)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_8,

    // Tiled draw tests (40x40 source, tiled to fill screen)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_8,

    // Tiled resize tests (160x160 source, resize-filled into 160x160 screen tiles)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_8,

    // Tiled rotate tests (80x80 source, rotated 45 in 80x80 slots)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_8,

    // Text transform (rotation + scale)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_NONE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_RESIZE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_DOUBLE,

    // Text transform buffered (rotation + scale)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_BUFFERED_NONE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_BUFFERED,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_BUFFERED_RESIZE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_BUFFERED_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_BUFFERED_DOUBLE,

    // External text transform (rotation)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_ROTATE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_ROTATE_BUFFERED,

    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MAX,
};

typedef struct egui_view_test_performance egui_view_test_performance_t;
struct egui_view_test_performance
{
    egui_view_t base;

    int test_mode;
};

void egui_view_test_performance_init(egui_view_t *self);
int egui_view_test_performance_is_enabled(int test_mode);

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _EGUI_VIEW_TEST_PERFORMANCE_H_ */
