#ifndef _EGUI_VIEW_TEST_PERFORMANCE_H_
#define _EGUI_VIEW_TEST_PERFORMANCE_H_

#include "widget/egui_view.h"

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

enum
{
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_LINE = 0x0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_RECTANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_CORNERS,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_RECTANGLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_CORNERS_FILL,

    // Triangle
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL,

    // Ellipse (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_ELLIPSE)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ELLIPSE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ELLIPSE_FILL,

    // Polygon (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_POLYGON)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_POLYGON,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_POLYGON_FILL,

    // Bezier (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_BEZIER)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_BEZIER_QUAD,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_BEZIER_CUBIC,

    // HQ circle/arc (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_CIRCLE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_FILL_HQ,

    // HQ line (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_LINE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_LINE_HQ,

    // Gradient (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_GRADIENT)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_TRIANGLE,

    // Shadow (EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_SHADOW,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_SHADOW_ROUND,

    // Mask performance tests
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_ROUND_RECT_FILL_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_ROUND_RECT_FILL_WITH_MASK,

    // Animation performance tests
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_TRANSLATE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_ALPHA,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_SCALE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_SET,

    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MAX,
};

typedef struct egui_view_test_performance egui_view_test_performance_t;
struct egui_view_test_performance
{
    egui_view_t base;

    int test_mode;
};

void egui_view_test_performance_init(egui_view_t *self);
int egui_view_test_performance_is_enabled(int test_mode);

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _EGUI_VIEW_TEST_PERFORMANCE_H_ */
