#ifndef _MAIN_PAGE_H_
#define _MAIN_PAGE_H_

// ===== Auto-generated by EmbeddedGUI Designer =====
// This file is regenerated when the layout changes.
// Only the USER CODE regions are preserved.

#include "egui.h"

// USER CODE BEGIN includes
#include "my_custom.h"
#include "sensors.h"
// USER CODE END includes

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

typedef struct egui_main_page egui_main_page_t;
struct egui_main_page
{
    egui_page_base_t base;

    // UI widgets (auto-generated, do not edit)
    egui_view_group_t root_group;
    egui_view_label_t my_label;

    // USER CODE BEGIN user_fields
    int my_counter;
    float my_timer;
    uint8_t sensor_data[32];
    // USER CODE END user_fields
};

// Layout init (auto-generated in main_page_layout.c)
void egui_main_page_layout_init(egui_page_base_t *self);

// Page init (user-implemented in main_page.c)
void egui_main_page_init(egui_page_base_t *self);

// USER CODE BEGIN declarations
void my_custom_func(void);
int get_sensor_value(int channel);
// USER CODE END declarations

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _MAIN_PAGE_H_ */
