#ifndef _EGUI_VIEW_TEST_PERFORMANCE_H_
#define _EGUI_VIEW_TEST_PERFORMANCE_H_

#include "widget/egui_view.h"

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

enum
{
    // ========================================================================
    // Category 1: Basic Shapes
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_LINE = 0x0,

    // HQ line (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_LINE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_LINE_HQ,

    // Rectangle
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_RECTANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_RECTANGLE_FILL,

    // Circle
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL,
    // HQ circle (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_CIRCLE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_HQ,

    // Arc
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_FILL,
    // HQ arc (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_CIRCLE_HQ)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_HQ,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ARC_FILL_HQ,

    // Round rectangle
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_CORNERS,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_CORNERS_FILL,

    // Triangle
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL,

    // Ellipse (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_ELLIPSE)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ELLIPSE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ELLIPSE_FILL,

    // Polygon (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_POLYGON)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_POLYGON,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_POLYGON_FILL,

    // Bezier (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_BEZIER)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_BEZIER_QUAD,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_BEZIER_CUBIC,

    // Shape fill multi-size (quarter / double)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CIRCLE_FILL_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ROUND_RECTANGLE_FILL_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TRIANGLE_FILL_DOUBLE,

    // ========================================================================
    // Category 2: Text
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_INTERNAL_TEXT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_INTERNAL_TEXT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_INTERNAL_TEXT_RLE4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_INTERNAL_TEXT_RECT_RLE4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_INTERNAL_TEXT_RLE4_XOR,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_INTERNAL_TEXT_RECT_RLE4_XOR,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_RLE4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_RECT_RLE4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_RLE4_XOR,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_RECT_RLE4_XOR,

    // Text transform (rotation + scale)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_NONE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_RESIZE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_DOUBLE,

    // External text transform (rotation)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_TEXT_ROTATE,

    // ========================================================================
    // Category 3: Image direct draw (RGB565)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8,

    // Image direct draw multi-size
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_565_8_DOUBLE,

    // Extern image direct draw
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_565_8,

    // Tiled draw tests (40x40 source, tiled to fill screen)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_STAR_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_TILED_565_8,

    // ========================================================================
    // Category 4: Image resize (RGB565)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_565_8,

    // Extern image resize
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_565_8,

    // Star image resize (real alpha, image source: star.png)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_STAR_565_8,

    // Tiled resize tests (160x160 source, resize-filled into 160x160 screen tiles)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_TILED_STAR_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RESIZE_TILED_565_8,

    // ========================================================================
    // Category 5: Image rotate (RGB565)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_RESIZE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_565_DOUBLE,

    // External image rotate
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_565_8,

    // Star image rotate (real alpha, image source: star.png)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_STAR_565_8,

    // Tiled rotate tests (80x80 source, rotated 45 in 80x80 slots)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_ROTATE_TILED_STAR_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_TILED_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_TILED_565_1,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_TILED_565_2,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_TILED_565_4,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_ROTATE_TILED_565_8,

    // ========================================================================
    // Category 6: Image color tint
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_COLOR,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RESIZE_COLOR,

    // ========================================================================
    // Category 7: Gradient (EGUI_CONFIG_FUNCTION_CANVAS_DRAW_GRADIENT)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_TRIANGLE,
    // Gradient extended: arc ring, radial, angular
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ARC_RING,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ARC_RING_ROUND_CAP,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_RADIAL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ANGULAR,
    // Gradient extended: ring stroke, capsule line
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ROUND_RECT_RING,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_LINE_CAPSULE,
    // Gradient extended: multi-stop, per-corner
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_MULTI_STOP,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_GRADIENT_ROUND_RECT_CORNERS,
    // Image + gradient overlay
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_GRADIENT_OVERLAY,
    // Mask + gradient overlay
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_GRADIENT_RECT_FILL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_GRADIENT_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_GRADIENT_IMAGE_ROTATE,
    // Text with gradient color overlay (egui_mask_gradient_t)
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_GRADIENT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_RECT_GRADIENT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_TEXT_ROTATE_GRADIENT,

    // ========================================================================
    // Category 8: Shadow (EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_SHADOW,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_SHADOW_ROUND,

    // ========================================================================
    // Category 9: Mask
    // ========================================================================
    // Rect fill + mask
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_NO_MASK_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_ROUND_RECT_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_CIRCLE_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_RECT_FILL_IMAGE_DOUBLE,
    // Image + mask
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_NO_MASK_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_ROUND_RECT_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_CIRCLE_DOUBLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE_QUARTER,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_IMAGE_DOUBLE,
    // Round rect fill + mask
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_ROUND_RECT_FILL_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_ROUND_RECT_FILL_WITH_MASK,

    // ========================================================================
    // Category 10: Animation
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_TRANSLATE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_ALPHA,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_SCALE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_ANIMATION_SET,

    // ========================================================================
    // Category 11: Mask image with opaque test_perf source
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_TEST_PERF_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_TEST_PERF_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_TEST_PERF_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_TEST_PERF_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_TEST_PERF_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_TEST_PERF_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_TEST_PERF_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_TEST_PERF_IMAGE,

    // ========================================================================
    // Category 12: Compressed Image (QOI)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_QOI_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_QOI_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_QOI_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_QOI_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_QOI_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_QOI_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_8_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_8_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_8_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_QOI_8_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_8_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_8_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_8_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_QOI_8_IMAGE,

    // ========================================================================
    // Category 13: Compressed Image (RLE)
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RLE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_RLE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RLE_565,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_IMAGE_RLE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_RLE_565_0,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_IMAGE_TILED_RLE_565_8,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_8_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_8_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_8_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MASK_IMAGE_RLE_8_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_IMAGE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_8_NO_MASK,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_8_ROUND_RECT,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_8_CIRCLE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_EXTERN_MASK_IMAGE_RLE_8_IMAGE,

    // ========================================================================
    // Category 14: File image and heavy widgets
    // ========================================================================
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_FILE_IMAGE_BMP_NORMAL,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_FILE_IMAGE_JPG,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_FILE_IMAGE_PNG,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_FILE_IMAGE_BMP,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CHART_LINE_DENSE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CHART_BAR_DENSE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CHART_SCATTER_DENSE,
    EGUI_VIEW_TEST_PERFORMANCE_TYPE_CHART_PIE_DENSE,

    EGUI_VIEW_TEST_PERFORMANCE_TYPE_MAX,
};

typedef struct egui_view_test_performance egui_view_test_performance_t;
struct egui_view_test_performance
{
    egui_view_t base;

    int test_mode;
};

void egui_view_test_performance_init(egui_view_t *self);
int egui_view_test_performance_is_enabled(int test_mode);

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _EGUI_VIEW_TEST_PERFORMANCE_H_ */
