#ifndef _EGUI_CONFIG_VALIDATE_H_
#define _EGUI_CONFIG_VALIDATE_H_

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

#if (EGUI_CONFIG_COLOR_DEPTH != 8) && (EGUI_CONFIG_COLOR_DEPTH != 16) && (EGUI_CONFIG_COLOR_DEPTH != 32)
#error "EGUI_CONFIG_COLOR_DEPTH must be 8, 16, or 32."
#endif

#if EGUI_CONFIG_COLOR_DEPTH == 8
#define EGUI_CONFIG_VALIDATE_COLOR_BYTES 1
#elif EGUI_CONFIG_COLOR_DEPTH == 16
#define EGUI_CONFIG_VALIDATE_COLOR_BYTES 2
#elif EGUI_CONFIG_COLOR_DEPTH == 32
#define EGUI_CONFIG_VALIDATE_COLOR_BYTES 4
#else
#define EGUI_CONFIG_VALIDATE_COLOR_BYTES 1
#endif

#if (EGUI_CONFIG_SCREEN_WIDTH <= 0) || (EGUI_CONFIG_SCREEN_HEIGHT <= 0)
#error "EGUI_CONFIG_SCREEN_WIDTH and EGUI_CONFIG_SCREEN_HEIGHT must be > 0."
#endif

#if (EGUI_CONFIG_SCREEN_WIDTH > 32767) || (EGUI_CONFIG_SCREEN_HEIGHT > 32767)
#error "EGUI_CONFIG_SCREEN_WIDTH and EGUI_CONFIG_SCREEN_HEIGHT must fit in int16_t."
#endif

#if (EGUI_CONFIG_PFB_WIDTH <= 0) || (EGUI_CONFIG_PFB_HEIGHT <= 0)
#error "EGUI_CONFIG_PFB_WIDTH and EGUI_CONFIG_PFB_HEIGHT must be > 0."
#endif

#if (EGUI_CONFIG_PFB_WIDTH > 32767) || (EGUI_CONFIG_PFB_HEIGHT > 32767)
#error "EGUI_CONFIG_PFB_WIDTH and EGUI_CONFIG_PFB_HEIGHT must fit in int16_t."
#endif

#if (EGUI_CONFIG_PFB_BUFFER_COUNT <= 0) || (EGUI_CONFIG_PFB_BUFFER_COUNT > 4)
#error "EGUI_CONFIG_PFB_BUFFER_COUNT must be in range 1..4."
#endif

#if (EGUI_CONFIG_PFB_BUFFER_COUNT >= 1) && (EGUI_CONFIG_PFB_BUFFER_COUNT <= 4)
#define EGUI_CONFIG_VALIDATE_PFB_BUFFER_COUNT EGUI_CONFIG_PFB_BUFFER_COUNT
#else
#define EGUI_CONFIG_VALIDATE_PFB_BUFFER_COUNT 1
#endif

#if (EGUI_CONFIG_PFB_WIDTH > 0)
#define EGUI_CONFIG_VALIDATE_PFB_WIDTH EGUI_CONFIG_PFB_WIDTH
#else
#define EGUI_CONFIG_VALIDATE_PFB_WIDTH 1
#endif

#if (EGUI_CONFIG_PFB_HEIGHT > 0)
#define EGUI_CONFIG_VALIDATE_PFB_HEIGHT EGUI_CONFIG_PFB_HEIGHT
#else
#define EGUI_CONFIG_VALIDATE_PFB_HEIGHT 1
#endif

#if (EGUI_CONFIG_VALIDATE_PFB_WIDTH > (2147483647 / EGUI_CONFIG_VALIDATE_COLOR_BYTES / EGUI_CONFIG_VALIDATE_PFB_HEIGHT))
#error "One PFB buffer must fit in int-sized byte counts."
#endif

#if (EGUI_CONFIG_VALIDATE_PFB_WIDTH > (2147483647 / EGUI_CONFIG_VALIDATE_COLOR_BYTES / EGUI_CONFIG_VALIDATE_PFB_BUFFER_COUNT / EGUI_CONFIG_VALIDATE_PFB_HEIGHT))
#error "All configured PFB buffers must fit in int-sized byte counts."
#endif

#if (EGUI_CONFIG_DIRTY_AREA_COUNT <= 0)
#error "EGUI_CONFIG_DIRTY_AREA_COUNT must be > 0."
#endif

#if (EGUI_CONFIG_MAX_FPS <= 0)
#error "EGUI_CONFIG_MAX_FPS must be > 0."
#endif

#if (EGUI_CONFIG_MAX_DISPLAY_COUNT <= 0)
#error "EGUI_CONFIG_MAX_DISPLAY_COUNT must be > 0."
#endif

#if (EGUI_CONFIG_MAX_DISPLAY_COUNT > 255)
#error "EGUI_CONFIG_MAX_DISPLAY_COUNT must fit in uint8_t display_id."
#endif

#if (EGUI_CONFIG_CORE_LOGICAL_PFB_PROBE_ENABLE != 0) && (EGUI_CONFIG_CORE_LOGICAL_PFB_PROBE_ENABLE != 1)
#error "EGUI_CONFIG_CORE_LOGICAL_PFB_PROBE_ENABLE must be 0 or 1."
#endif

#if EGUI_CONFIG_CORE_LOGICAL_PFB_PROBE_ENABLE && (EGUI_CONFIG_CORE_LOGICAL_PFB_PROBE_TARGET_WIDTH <= 0)
#error "EGUI_CONFIG_CORE_LOGICAL_PFB_PROBE_TARGET_WIDTH must be > 0 when logical PFB probe is enabled."
#endif

#if (EGUI_CONFIG_CORE_SEPARATE_USER_ROOT_GROUP_ENABLE != 0) && (EGUI_CONFIG_CORE_SEPARATE_USER_ROOT_GROUP_ENABLE != 1)
#error "EGUI_CONFIG_CORE_SEPARATE_USER_ROOT_GROUP_ENABLE must be 0 or 1."
#endif

#if (EGUI_CONFIG_PERFORMANCE_USE_FLOAT != 0) && (EGUI_CONFIG_PERFORMANCE_USE_FLOAT != 1)
#error "EGUI_CONFIG_PERFORMANCE_USE_FLOAT must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC_LIBC_FALLBACK != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC_LIBC_FALLBACK != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC_LIBC_FALLBACK must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_MEMORY_OP != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_MEMORY_OP != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_MEMORY_OP must be 0 or 1."
#endif

#if (EGUI_CONFIG_INPUT_MOTION_CACHE_COUNT <= 0)
#error "EGUI_CONFIG_INPUT_MOTION_CACHE_COUNT must be > 0."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_ACTIVITY != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_ACTIVITY != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_ACTIVITY must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_DIALOG != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_DIALOG != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_DIALOG must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_TOAST != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_TOAST != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_TOAST must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_MULTI_TOUCH != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_MULTI_TOUCH != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_MULTI_TOUCH must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_INPUT_VELOCITY_TRACKER != 0) && (EGUI_CONFIG_FUNCTION_INPUT_VELOCITY_TRACKER != 1)
#error "EGUI_CONFIG_FUNCTION_INPUT_VELOCITY_TRACKER must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_KEY != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_KEY != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_KEY must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_LAYER != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_LAYER != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_LAYER must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_MASK != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_MASK != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_MASK must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR must be 0 or 1."
#endif

#if EGUI_CONFIG_FUNCTION_SUPPORT_KEY && (EGUI_CONFIG_INPUT_KEY_CACHE_COUNT <= 0)
#error "EGUI_CONFIG_INPUT_KEY_CACHE_COUNT must be > 0 when key support is enabled."
#endif

#if EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH && (EGUI_CONFIG_TOUCH_CAPTURE_PATH_MAX <= 0)
#error "EGUI_CONFIG_TOUCH_CAPTURE_PATH_MAX must be > 0 when touch support is enabled."
#endif

#if (EGUI_CONFIG_TEXTINPUT_MAX_LENGTH <= 0) || (EGUI_CONFIG_TEXTINPUT_MAX_LENGTH > 255)
#error "EGUI_CONFIG_TEXTINPUT_MAX_LENGTH must be in range 1..255."
#endif

#if (EGUI_CONFIG_TEXTBLOCK_EDIT_MAX_LENGTH <= 0) || (EGUI_CONFIG_TEXTBLOCK_EDIT_MAX_LENGTH > 65535)
#error "EGUI_CONFIG_TEXTBLOCK_EDIT_MAX_LENGTH must be in range 1..65535."
#endif

#if (EGUI_CONFIG_WIDGET_AUTO_ICON_FONT_FALLBACK != 0) && (EGUI_CONFIG_WIDGET_AUTO_ICON_FONT_FALLBACK != 1)
#error "EGUI_CONFIG_WIDGET_AUTO_ICON_FONT_FALLBACK must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_VIEW_BUTTON_ICON != 0) && (EGUI_CONFIG_FUNCTION_VIEW_BUTTON_ICON != 1)
#error "EGUI_CONFIG_FUNCTION_VIEW_BUTTON_ICON must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_EXTERNAL_RESOURCE != 0) && (EGUI_CONFIG_FUNCTION_EXTERNAL_RESOURCE != 1)
#error "EGUI_CONFIG_FUNCTION_EXTERNAL_RESOURCE must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_RESOURCE_MANAGER != 0) && (EGUI_CONFIG_FUNCTION_RESOURCE_MANAGER != 1)
#error "EGUI_CONFIG_FUNCTION_RESOURCE_MANAGER must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FILE != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FILE != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FILE must be 0 or 1."
#endif

#if EGUI_CONFIG_FUNCTION_IMAGE_FILE && ((EGUI_CONFIG_IMAGE_FILE_DECODER_MAX_COUNT <= 0) || (EGUI_CONFIG_IMAGE_FILE_DECODER_MAX_COUNT > 255))
#error "EGUI_CONFIG_IMAGE_FILE_DECODER_MAX_COUNT must be in range 1..255 when image-file support is enabled."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB32 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB32 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB32 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_1 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_1 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_1 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_2 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_2 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_2 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_4 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_4 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_4 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_1 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_1 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_1 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_2 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_2 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_2 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_4 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_4 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_4 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8 != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8 != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_CODEC_QOI != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_CODEC_QOI != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_CODEC_QOI must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_CODEC_RLE != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_CODEC_RLE != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_CODEC_RLE must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG != 0) && (EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG != 1)
#error "EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG must be 0 or 1."
#endif

#if EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG && (!EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565 || !EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8)
#error "EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG requires EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565=1 and EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8=1."
#endif

#if EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB32 && (EGUI_CONFIG_IMAGE_DECODE_MAX_PIXEL_SIZE < 4)
#error "EGUI_CONFIG_IMAGE_DECODE_MAX_PIXEL_SIZE must be >= 4 when RGB32 image format support is enabled."
#endif

#if (EGUI_CONFIG_IMAGE_DECODE_MAX_PIXEL_SIZE <= 0)
#error "EGUI_CONFIG_IMAGE_DECODE_MAX_PIXEL_SIZE must be > 0."
#endif

#if (EGUI_CONFIG_FUNCTION_IMAGE_CODEC_FAST_DRAW < 0) || (EGUI_CONFIG_FUNCTION_IMAGE_CODEC_FAST_DRAW > 2)
#error "EGUI_CONFIG_FUNCTION_IMAGE_CODEC_FAST_DRAW must be 0, 1 or 2."
#endif

#if (EGUI_CONFIG_IMAGE_CODEC_PERSISTENT_CACHE_MAX_BYTES < 0)
#error "EGUI_CONFIG_IMAGE_CODEC_PERSISTENT_CACHE_MAX_BYTES must be >= 0."
#endif

#if (EGUI_CONFIG_IMAGE_EXTERNAL_PERSISTENT_CACHE_MAX_BYTES < 0)
#error "EGUI_CONFIG_IMAGE_EXTERNAL_PERSISTENT_CACHE_MAX_BYTES must be >= 0."
#endif

#if (EGUI_CONFIG_IMAGE_RLE_EXTERNAL_CACHE_WINDOW_SIZE <= 0) || (EGUI_CONFIG_IMAGE_RLE_EXTERNAL_CACHE_WINDOW_SIZE > 65535)
#error "EGUI_CONFIG_IMAGE_RLE_EXTERNAL_CACHE_WINDOW_SIZE must be in range 1..65535."
#endif

#if (EGUI_CONFIG_IMAGE_DECODE_ROW_BUF_WIDTH <= 0)
#error "EGUI_CONFIG_IMAGE_DECODE_ROW_BUF_WIDTH must be > 0."
#endif

#if (EGUI_CONFIG_IMAGE_EXTERNAL_DATA_CACHE_MAX_BYTES < 0)
#error "EGUI_CONFIG_IMAGE_EXTERNAL_DATA_CACHE_MAX_BYTES must be >= 0."
#endif

#if (EGUI_CONFIG_IMAGE_EXTERNAL_ALPHA_CACHE_MAX_BYTES < 0)
#error "EGUI_CONFIG_IMAGE_EXTERNAL_ALPHA_CACHE_MAX_BYTES must be >= 0."
#endif

#if (EGUI_CONFIG_REDUCE_IMAGE_CODE_SIZE != 0) && (EGUI_CONFIG_REDUCE_IMAGE_CODE_SIZE != 1)
#error "EGUI_CONFIG_REDUCE_IMAGE_CODE_SIZE must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_VIEW_LABEL_COMPACT_ONLY != 0) && (EGUI_CONFIG_FUNCTION_VIEW_LABEL_COMPACT_ONLY != 1)
#error "EGUI_CONFIG_FUNCTION_VIEW_LABEL_COMPACT_ONLY must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_VIEW_LABEL_COMPACT_FALLBACK != 0) && (EGUI_CONFIG_FUNCTION_VIEW_LABEL_COMPACT_FALLBACK != 1)
#error "EGUI_CONFIG_FUNCTION_VIEW_LABEL_COMPACT_FALLBACK must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SUPPORT_MARGIN_PADDING != 0) && (EGUI_CONFIG_FUNCTION_SUPPORT_MARGIN_PADDING != 1)
#error "EGUI_CONFIG_FUNCTION_SUPPORT_MARGIN_PADDING must be 0 or 1."
#endif

#if (EGUI_CONFIG_REDUCE_MARGIN_PADDING_SIZE != 0) && (EGUI_CONFIG_REDUCE_MARGIN_PADDING_SIZE != 1)
#error "EGUI_CONFIG_REDUCE_MARGIN_PADDING_SIZE must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_RECORDING_TEST != 0) && (EGUI_CONFIG_FUNCTION_RECORDING_TEST != 1)
#error "EGUI_CONFIG_FUNCTION_RECORDING_TEST must be 0 or 1."
#endif

#if (EGUI_CONFIG_TEXTINPUT_CURSOR_BLINK_MS <= 0)
#error "EGUI_CONFIG_TEXTINPUT_CURSOR_BLINK_MS must be > 0."
#endif

#if (EGUI_CONFIG_TEXTBLOCK_CURSOR_BLINK_MS <= 0)
#error "EGUI_CONFIG_TEXTBLOCK_CURSOR_BLINK_MS must be > 0."
#endif

#if (EGUI_CONFIG_CIRCLE_SUPPORT_RADIUS_BASIC_RANGE <= 0)
#error "EGUI_CONFIG_CIRCLE_SUPPORT_RADIUS_BASIC_RANGE must be > 0."
#endif

#if (EGUI_CONFIG_FUNCTION_CANVAS_EXTRA_CLIP != 0) && (EGUI_CONFIG_FUNCTION_CANVAS_EXTRA_CLIP != 1)
#error "EGUI_CONFIG_FUNCTION_CANVAS_EXTRA_CLIP must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_CANVAS_SPEC_CIRCLE_INFO != 0) && (EGUI_CONFIG_FUNCTION_CANVAS_SPEC_CIRCLE_INFO != 1)
#error "EGUI_CONFIG_FUNCTION_CANVAS_SPEC_CIRCLE_INFO must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_CANVAS_COMPACT_NUMBER != 0) && (EGUI_CONFIG_FUNCTION_CANVAS_COMPACT_NUMBER != 1)
#error "EGUI_CONFIG_FUNCTION_CANVAS_COMPACT_NUMBER must be 0 or 1."
#endif

#if (EGUI_CONFIG_CIRCLE_DEFAULT_ALGO_HQ != 0) && (EGUI_CONFIG_CIRCLE_DEFAULT_ALGO_HQ != 1)
#error "EGUI_CONFIG_CIRCLE_DEFAULT_ALGO_HQ must be 0 or 1."
#endif

#if (EGUI_CONFIG_CIRCLE_FILL_BASIC != 0) && (EGUI_CONFIG_CIRCLE_FILL_BASIC != 1)
#error "EGUI_CONFIG_CIRCLE_FILL_BASIC must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_WIDGET_ENHANCED_DRAW != 0) && (EGUI_CONFIG_FUNCTION_WIDGET_ENHANCED_DRAW != 1)
#error "EGUI_CONFIG_FUNCTION_WIDGET_ENHANCED_DRAW must be 0 or 1."
#endif

#if (EGUI_CONFIG_CIRCLE_HQ_INT32_ONLY != 0) && (EGUI_CONFIG_CIRCLE_HQ_INT32_ONLY != 1)
#error "EGUI_CONFIG_CIRCLE_HQ_INT32_ONLY must be 0 or 1."
#endif

#if (EGUI_CONFIG_CIRCLE_HQ_MAX_RADIUS <= 0)
#error "EGUI_CONFIG_CIRCLE_HQ_MAX_RADIUS must be > 0."
#endif

#if (EGUI_CONFIG_CIRCLE_HQ_SAMPLE_2X2 != 0) && (EGUI_CONFIG_CIRCLE_HQ_SAMPLE_2X2 != 1)
#error "EGUI_CONFIG_CIRCLE_HQ_SAMPLE_2X2 must be 0 or 1."
#endif

#if (EGUI_CONFIG_LINE_HQ_SAMPLE_2X2 != 0) && (EGUI_CONFIG_LINE_HQ_SAMPLE_2X2 != 1)
#error "EGUI_CONFIG_LINE_HQ_SAMPLE_2X2 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_GRADIENT_DITHERING != 0) && (EGUI_CONFIG_FUNCTION_GRADIENT_DITHERING != 1)
#error "EGUI_CONFIG_FUNCTION_GRADIENT_DITHERING must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_FONT_FORMAT_1 != 0) && (EGUI_CONFIG_FUNCTION_FONT_FORMAT_1 != 1)
#error "EGUI_CONFIG_FUNCTION_FONT_FORMAT_1 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_FONT_FORMAT_2 != 0) && (EGUI_CONFIG_FUNCTION_FONT_FORMAT_2 != 1)
#error "EGUI_CONFIG_FUNCTION_FONT_FORMAT_2 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_FONT_FORMAT_4 != 0) && (EGUI_CONFIG_FUNCTION_FONT_FORMAT_4 != 1)
#error "EGUI_CONFIG_FUNCTION_FONT_FORMAT_4 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_FONT_FORMAT_8 != 0) && (EGUI_CONFIG_FUNCTION_FONT_FORMAT_8 != 1)
#error "EGUI_CONFIG_FUNCTION_FONT_FORMAT_8 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4 != 0) && (EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4 != 1)
#error "EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4 must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4_XOR != 0) && (EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4_XOR != 1)
#error "EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4_XOR must be 0 or 1."
#endif

#if (EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_MAX_GLYPHS < 0) || (EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_SLOTS < 0)
#error "EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_* values must be >= 0."
#endif

#if ((EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_MAX_GLYPHS > 0) && (EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_SLOTS <= 0)) ||                                        \
        ((EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_MAX_GLYPHS <= 0) && (EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_SLOTS > 0))
#error "EGUI_CONFIG_FONT_STD_DRAW_PREFIX_CACHE_MAX_GLYPHS and _SLOTS must be enabled or disabled together."
#endif

#if (EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_MAX_BYTES < 0) || (EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_SLOTS < 0)
#error "EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_* values must be >= 0."
#endif

#if ((EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_MAX_BYTES > 0) && (EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_SLOTS <= 0)) ||                               \
        ((EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_MAX_BYTES <= 0) && (EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_SLOTS > 0))
#error "EGUI_CONFIG_FONT_STD_COMPRESSED_GLYPH_CACHE_MAX_BYTES and _SLOTS must be enabled or disabled together."
#endif

#if !EGUI_CONFIG_FUNCTION_FONT_FORMAT_4 && (EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4 || EGUI_CONFIG_FUNCTION_FONT_STD_BITMAP_CODEC_RLE4_XOR)
#error "Std font RLE4 codecs require EGUI_CONFIG_FUNCTION_FONT_FORMAT_4=1."
#endif

#if (EGUI_CONFIG_DEBUG_VIEW_ID != 0) && (EGUI_CONFIG_DEBUG_VIEW_ID != 1)
#error "EGUI_CONFIG_DEBUG_VIEW_ID must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_PFB_REFRESH != 0) && (EGUI_CONFIG_DEBUG_PFB_REFRESH != 1)
#error "EGUI_CONFIG_DEBUG_PFB_REFRESH must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_DIRTY_REGION_REFRESH != 0) && (EGUI_CONFIG_DEBUG_DIRTY_REGION_REFRESH != 1)
#error "EGUI_CONFIG_DEBUG_DIRTY_REGION_REFRESH must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_PFB_DIRTY_REGION_CLEAR != 0) && (EGUI_CONFIG_DEBUG_PFB_DIRTY_REGION_CLEAR != 1)
#error "EGUI_CONFIG_DEBUG_PFB_DIRTY_REGION_CLEAR must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_REFRESH_DELAY < 0)
#error "EGUI_CONFIG_DEBUG_REFRESH_DELAY must be >= 0."
#endif

#if (EGUI_CONFIG_DEBUG_DIRTY_REGION_DETAIL != 0) && (EGUI_CONFIG_DEBUG_DIRTY_REGION_DETAIL != 1)
#error "EGUI_CONFIG_DEBUG_DIRTY_REGION_DETAIL must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_DIRTY_REGION_TRACE != 0) && (EGUI_CONFIG_DEBUG_DIRTY_REGION_TRACE != 1)
#error "EGUI_CONFIG_DEBUG_DIRTY_REGION_TRACE must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_PERF_MONITOR_SHOW != 0) && (EGUI_CONFIG_DEBUG_PERF_MONITOR_SHOW != 1)
#error "EGUI_CONFIG_DEBUG_PERF_MONITOR_SHOW must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_MEM_MONITOR_SHOW != 0) && (EGUI_CONFIG_DEBUG_MEM_MONITOR_SHOW != 1)
#error "EGUI_CONFIG_DEBUG_MEM_MONITOR_SHOW must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_MONITOR_REFR_PERIOD <= 0)
#error "EGUI_CONFIG_DEBUG_MONITOR_REFR_PERIOD must be > 0."
#endif

#if (EGUI_CONFIG_DEBUG_CLASS_NAME != 0) && (EGUI_CONFIG_DEBUG_CLASS_NAME != 1)
#error "EGUI_CONFIG_DEBUG_CLASS_NAME must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_LOG_SIMPLE != 0) && (EGUI_CONFIG_DEBUG_LOG_SIMPLE != 1)
#error "EGUI_CONFIG_DEBUG_LOG_SIMPLE must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_DIRTY_REGION_STATS != 0) && (EGUI_CONFIG_DEBUG_DIRTY_REGION_STATS != 1)
#error "EGUI_CONFIG_DEBUG_DIRTY_REGION_STATS must be 0 or 1."
#endif

#if (EGUI_CONFIG_DEBUG_TOUCH_TRACE != 0) && (EGUI_CONFIG_DEBUG_TOUCH_TRACE != 1)
#error "EGUI_CONFIG_DEBUG_TOUCH_TRACE must be 0 or 1."
#endif

#if EGUI_CONFIG_DEBUG_TOUCH_TRACE && (EGUI_CONFIG_DEBUG_TOUCH_TRACE_MAX_POINTS <= 0)
#error "EGUI_CONFIG_DEBUG_TOUCH_TRACE_MAX_POINTS must be > 0 when touch trace is enabled."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_HEAP_ENABLE != 0) && (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_HEAP_ENABLE != 1)
#error "EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_HEAP_ENABLE must be 0 or 1."
#endif

#if !EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_HEAP_ENABLE && EGUI_CONFIG_FUNCTION_FONT_TRANSFORM_FAST_DRAW
#error "EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_HEAP_ENABLE=0 requires EGUI_CONFIG_FUNCTION_FONT_TRANSFORM_FAST_DRAW=0."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_PIXEL_INDEX_16BIT != 0) && (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_PIXEL_INDEX_16BIT != 1)
#error "EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_PIXEL_INDEX_16BIT must be 0 or 1."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_LINE_INDEX_16BIT != 0) && (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_LINE_INDEX_16BIT != 1)
#error "EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_LINE_INDEX_16BIT must be 0 or 1."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_VISIBLE_ALPHA8_MAX_BYTES < 0) || (EGUI_CONFIG_TEXT_TRANSFORM_VISIBLE_ALPHA8_STACK_MAX_BYTES < 0)
#error "EGUI_CONFIG_TEXT_TRANSFORM_VISIBLE_ALPHA8_* values must be >= 0."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_SCRATCH_HEAP_ENABLE != 0) && (EGUI_CONFIG_TEXT_TRANSFORM_SCRATCH_HEAP_ENABLE != 1)
#error "EGUI_CONFIG_TEXT_TRANSFORM_SCRATCH_HEAP_ENABLE must be 0 or 1."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_GLYPHS < 0) || (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_LINES < 0)
#error "EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_* values must be >= 0."
#endif

#if ((EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_GLYPHS > 0) && (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_LINES <= 0)) ||                                  \
        ((EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_GLYPHS <= 0) && (EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_LINES > 0))
#error "EGUI_CONFIG_TEXT_TRANSFORM_LAYOUT_STACK_MAX_GLYPHS and _LINES must be enabled or disabled together."
#endif

#if (EGUI_CONFIG_TEXT_TRANSFORM_TILE_MAX_GLYPHS <= 0) || (EGUI_CONFIG_TEXT_TRANSFORM_TILE_MAX_LINES <= 0)
#error "EGUI_CONFIG_TEXT_TRANSFORM_TILE_MAX_GLYPHS and _LINES must be > 0."
#endif

#if (EGUI_CONFIG_SHADOW_DSQ_LUT_MAX <= 0) || (EGUI_CONFIG_SHADOW_DSQ_LUT_MAX > 4096)
#error "EGUI_CONFIG_SHADOW_DSQ_LUT_MAX must be in range 1..4096."
#endif

#if (EGUI_CONFIG_FUNCTION_VIEW_GROUP_TOUCH_CAPTURE_PATH != 0) && (EGUI_CONFIG_FUNCTION_VIEW_GROUP_TOUCH_CAPTURE_PATH != 1)
#error "EGUI_CONFIG_FUNCTION_VIEW_GROUP_TOUCH_CAPTURE_PATH must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_CORE_PRE_COMPUTE_SCROLL != 0) && (EGUI_CONFIG_FUNCTION_CORE_PRE_COMPUTE_SCROLL != 1)
#error "EGUI_CONFIG_FUNCTION_CORE_PRE_COMPUTE_SCROLL must be 0 or 1."
#endif

#if (EGUI_CONFIG_COLOR_16_SWAP != 0) && (EGUI_CONFIG_COLOR_16_SWAP != 1)
#error "EGUI_CONFIG_COLOR_16_SWAP must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SOFTWARE_ROTATION_ENABLE != 0) && (EGUI_CONFIG_FUNCTION_SOFTWARE_ROTATION_ENABLE != 1)
#error "EGUI_CONFIG_FUNCTION_SOFTWARE_ROTATION_ENABLE must be 0 or 1."
#endif

#undef EGUI_CONFIG_VALIDATE_COLOR_BYTES
#undef EGUI_CONFIG_VALIDATE_PFB_BUFFER_COUNT
#undef EGUI_CONFIG_VALIDATE_PFB_WIDTH
#undef EGUI_CONFIG_VALIDATE_PFB_HEIGHT

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _EGUI_CONFIG_VALIDATE_H_ */
