#ifndef _EGUI_CONFIG_VALIDATE_H_
#define _EGUI_CONFIG_VALIDATE_H_

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

#if (EGUI_CONFIG_COLOR_DEPTH != 8) && (EGUI_CONFIG_COLOR_DEPTH != 16) && (EGUI_CONFIG_COLOR_DEPTH != 32)
#error "EGUI_CONFIG_COLOR_DEPTH must be 8, 16, or 32."
#endif

#if (EGUI_CONFIG_SCEEN_WIDTH <= 0) || (EGUI_CONFIG_SCEEN_HEIGHT <= 0)
#error "EGUI_CONFIG_SCEEN_WIDTH and EGUI_CONFIG_SCEEN_HEIGHT must be > 0."
#endif

#if (EGUI_CONFIG_SCEEN_WIDTH > 32767) || (EGUI_CONFIG_SCEEN_HEIGHT > 32767)
#error "EGUI_CONFIG_SCEEN_WIDTH and EGUI_CONFIG_SCEEN_HEIGHT must fit in int16_t."
#endif

#if (EGUI_CONFIG_PFB_WIDTH <= 0) || (EGUI_CONFIG_PFB_HEIGHT <= 0)
#error "EGUI_CONFIG_PFB_WIDTH and EGUI_CONFIG_PFB_HEIGHT must be > 0."
#endif

#if (EGUI_CONFIG_PFB_WIDTH > 32767) || (EGUI_CONFIG_PFB_HEIGHT > 32767)
#error "EGUI_CONFIG_PFB_WIDTH and EGUI_CONFIG_PFB_HEIGHT must fit in int16_t."
#endif

#if (EGUI_CONFIG_PFB_BUFFER_COUNT <= 0) || (EGUI_CONFIG_PFB_BUFFER_COUNT > 4)
#error "EGUI_CONFIG_PFB_BUFFER_COUNT must be in range 1..4."
#endif

#if (EGUI_CONFIG_DIRTY_AREA_COUNT <= 0)
#error "EGUI_CONFIG_DIRTY_AREA_COUNT must be > 0."
#endif

#if (EGUI_CONFIG_MAX_FPS <= 0)
#error "EGUI_CONFIG_MAX_FPS must be > 0."
#endif

#if (EGUI_CONFIG_MAX_DISPLAY_COUNT <= 0)
#error "EGUI_CONFIG_MAX_DISPLAY_COUNT must be > 0."
#endif

#if (EGUI_CONFIG_MAX_DISPLAY_COUNT > 255)
#error "EGUI_CONFIG_MAX_DISPLAY_COUNT must fit in uint8_t display_id."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC_LIBC_FALLBACK != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC_LIBC_FALLBACK != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_MALLOC_LIBC_FALLBACK must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_PRINTF must be 0 or 1."
#endif

#if (EGUI_CONFIG_PLATFORM_CUSTOM_MEMORY_OP != 0) && (EGUI_CONFIG_PLATFORM_CUSTOM_MEMORY_OP != 1)
#error "EGUI_CONFIG_PLATFORM_CUSTOM_MEMORY_OP must be 0 or 1."
#endif

#if (EGUI_CONFIG_INPUT_MOTION_CACHE_COUNT <= 0)
#error "EGUI_CONFIG_INPUT_MOTION_CACHE_COUNT must be > 0."
#endif

#if (EGUI_CONFIG_FUNCTION_INPUT_VELOCITY_TRACKER != 0) && (EGUI_CONFIG_FUNCTION_INPUT_VELOCITY_TRACKER != 1)
#error "EGUI_CONFIG_FUNCTION_INPUT_VELOCITY_TRACKER must be 0 or 1."
#endif

#if EGUI_CONFIG_FUNCTION_SUPPORT_KEY && (EGUI_CONFIG_INPUT_KEY_CACHE_COUNT <= 0)
#error "EGUI_CONFIG_INPUT_KEY_CACHE_COUNT must be > 0 when key support is enabled."
#endif

#if EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH && (EGUI_CONFIG_TOUCH_CAPTURE_PATH_MAX <= 0)
#error "EGUI_CONFIG_TOUCH_CAPTURE_PATH_MAX must be > 0 when touch support is enabled."
#endif

#if (EGUI_CONFIG_TEXTINPUT_MAX_LENGTH <= 0) || (EGUI_CONFIG_TEXTINPUT_MAX_LENGTH > 255)
#error "EGUI_CONFIG_TEXTINPUT_MAX_LENGTH must be in range 1..255."
#endif

#if (EGUI_CONFIG_TEXTBLOCK_EDIT_MAX_LENGTH <= 0) || (EGUI_CONFIG_TEXTBLOCK_EDIT_MAX_LENGTH > 65535)
#error "EGUI_CONFIG_TEXTBLOCK_EDIT_MAX_LENGTH must be in range 1..65535."
#endif

#if EGUI_CONFIG_FUNCTION_IMAGE_FILE && ((EGUI_CONFIG_IMAGE_FILE_DECODER_MAX_COUNT <= 0) || (EGUI_CONFIG_IMAGE_FILE_DECODER_MAX_COUNT > 255))
#error "EGUI_CONFIG_IMAGE_FILE_DECODER_MAX_COUNT must be in range 1..255 when image-file support is enabled."
#endif

#if EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG && (!EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565 || !EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8)
#error "EGUI_CONFIG_FUNCTION_IMAGE_RUNTIME_SVG requires EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565=1 and EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8=1."
#endif

#if EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB32 && (EGUI_CONFIG_IMAGE_DECODE_MAX_PIXEL_SIZE < 4)
#error "EGUI_CONFIG_IMAGE_DECODE_MAX_PIXEL_SIZE must be >= 4 when RGB32 image format support is enabled."
#endif

#if (EGUI_CONFIG_IMAGE_RLE_EXTERNAL_CACHE_WINDOW_SIZE <= 0) || (EGUI_CONFIG_IMAGE_RLE_EXTERNAL_CACHE_WINDOW_SIZE > 65535)
#error "EGUI_CONFIG_IMAGE_RLE_EXTERNAL_CACHE_WINDOW_SIZE must be in range 1..65535."
#endif

#if (EGUI_CONFIG_FUNCTION_VIEW_GROUP_TOUCH_CAPTURE_PATH != 0) && (EGUI_CONFIG_FUNCTION_VIEW_GROUP_TOUCH_CAPTURE_PATH != 1)
#error "EGUI_CONFIG_FUNCTION_VIEW_GROUP_TOUCH_CAPTURE_PATH must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_CORE_PRE_COMPUTE_SCROLL != 0) && (EGUI_CONFIG_FUNCTION_CORE_PRE_COMPUTE_SCROLL != 1)
#error "EGUI_CONFIG_FUNCTION_CORE_PRE_COMPUTE_SCROLL must be 0 or 1."
#endif

#if (EGUI_CONFIG_COLOR_16_SWAP != 0) && (EGUI_CONFIG_COLOR_16_SWAP != 1)
#error "EGUI_CONFIG_COLOR_16_SWAP must be 0 or 1."
#endif

#if (EGUI_CONFIG_FUNCTION_SOFTWARE_ROTATION_ENABLE != 0) && (EGUI_CONFIG_FUNCTION_SOFTWARE_ROTATION_ENABLE != 1)
#error "EGUI_CONFIG_FUNCTION_SOFTWARE_ROTATION_ENABLE must be 0 or 1."
#endif

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _EGUI_CONFIG_VALIDATE_H_ */
