#ifndef _VIRTUAL_STAGE_SHOWCASE_APP_EGUI_RESOURCE_GENERATE_BRIDGE_H_
#define _VIRTUAL_STAGE_SHOWCASE_APP_EGUI_RESOURCE_GENERATE_BRIDGE_H_

#include "../../HelloShowcase/resource/app_egui_resource_generate.h"

#endif /* _VIRTUAL_STAGE_SHOWCASE_APP_EGUI_RESOURCE_GENERATE_BRIDGE_H_ */
