#ifndef _APP_EGUI_CONFIG_H_
#define _APP_EGUI_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define HELLO_VIRTUAL_STAGE_SHOWCASE_CANVAS_WIDTH  1280
#define HELLO_VIRTUAL_STAGE_SHOWCASE_CANVAS_HEIGHT 1024

// #define EGUI_CONFIG_SCEEN_WIDTH 240
// #define EGUI_CONFIG_SCEEN_HEIGHT 320

#ifndef EGUI_CONFIG_SCEEN_WIDTH
#if EGUI_CONFIG_RECORDING_TEST
#define EGUI_CONFIG_SCEEN_WIDTH HELLO_VIRTUAL_STAGE_SHOWCASE_CANVAS_WIDTH
#else
#define EGUI_CONFIG_SCEEN_WIDTH 240
#endif
#endif

#ifndef EGUI_CONFIG_SCEEN_HEIGHT
#if EGUI_CONFIG_RECORDING_TEST
#define EGUI_CONFIG_SCEEN_HEIGHT HELLO_VIRTUAL_STAGE_SHOWCASE_CANVAS_HEIGHT
#else
#define EGUI_CONFIG_SCEEN_HEIGHT 320
#endif
#endif

#ifndef EGUI_CONFIG_PFB_WIDTH
#define EGUI_CONFIG_PFB_WIDTH ((EGUI_CONFIG_SCEEN_WIDTH + 3) / 4)
#endif

#ifndef EGUI_CONFIG_PFB_HEIGHT
#define EGUI_CONFIG_PFB_HEIGHT ((EGUI_CONFIG_SCEEN_HEIGHT + 31) / 32)
#endif
#define EGUI_CONFIG_DIRTY_AREA_COUNT 16

#define EGUI_CONFIG_CIRCLE_SUPPORT_RADIUS_BASIC_RANGE 150
#define EGUI_CONFIG_WIDGET_ENHANCED_DRAW              1
#define EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW           1
#define EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS            1
#define EGUI_CONFIG_FUNCTION_SUPPORT_LAYER            1
#define EGUI_CONFIG_FUNCTION_SUPPORT_KEY              1

#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_CONFIG_H_ */
