#ifndef _APP_EGUI_CONFIG_H_
#define _APP_EGUI_CONFIG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define EGUI_CONFIG_FUNCTION_SUPPORT_MASK          1
#define EGUI_CONFIG_FUNCTION_IMAGE_CODEC_QOI       1
#define EGUI_CONFIG_FUNCTION_IMAGE_CODEC_RLE       1
#define EGUI_CONFIG_FUNCTION_WIDGET_ENHANCED_DRAW  1
#define EGUI_CONFIG_FUNCTION_SUPPORT_SHADOW        1
#define EGUI_CONFIG_FUNCTION_SUPPORT_LAYER         1
#define EGUI_CONFIG_FUNCTION_SUPPORT_SCROLLBAR     1
#define EGUI_CONFIG_FUNCTION_SUPPORT_TOUCH         1
#define EGUI_CONFIG_FUNCTION_SUPPORT_MULTI_TOUCH   1
#define EGUI_CONFIG_FUNCTION_SUPPORT_KEY           1
#define EGUI_CONFIG_FUNCTION_SUPPORT_FOCUS         1
#define EGUI_CONFIG_CIRCLE_DEFAULT_ALGO_HQ         0
#define EGUI_CONFIG_FUNCTION_FONT_STD_FAST_DRAW    1
#define EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565_8 1
#define EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8  1
#define EGUI_CONFIG_FUNCTION_ANIM_DELAY            1
#define EGUI_CONFIG_FUNCTION_ANIM_COMPLETE_CB      1
#define EGUI_CONFIG_FUNCTION_ANIM_PAUSE_RESUME     1
#define EGUI_CONFIG_FUNCTION_SCROLL_HORIZONTAL     1
#define EGUI_CONFIG_FUNCTION_LABEL_RECOLOR         1
#define EGUI_CONFIG_FUNCTION_VIEW_USER_DATA        1
#define EGUI_CONFIG_FUNCTION_LABEL_LETTER_SPACE    1
#define EGUI_CONFIG_FUNCTION_LABEL_WORD_WRAP       1
#define EGUI_CONFIG_FUNCTION_LABEL_TEXT_FMT        1
#define EGUI_CONFIG_FUNCTION_EXT_CLICK_AREA        1
#define EGUI_CONFIG_FUNCTION_LONG_PRESS            1
#define EGUI_CONFIG_FUNCTION_SWIPE_LISTENER        1
#define EGUI_CONFIG_FUNCTION_SCROLL_SNAP           1
#define EGUI_CONFIG_FUNCTION_DRAGGABLE_VIEW        1
#define EGUI_CONFIG_FUNCTION_IMAGE_TRANSFORM       1
#define EGUI_CONFIG_FUNCTION_LABEL_LONG_MODE       1
#define EGUI_CONFIG_FUNCTION_SCROLL_LISTENER       1

#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_CONFIG_H_ */
