EGUI_CODE_SRC		+= $(EGUI_PATH)
EGUI_CODE_SRC		+= $(EGUI_PATH)/app
EGUI_CODE_SRC		+= $(EGUI_PATH)/anim
EGUI_CODE_SRC		+= $(EGUI_PATH)/background
EGUI_CODE_SRC		+= $(EGUI_PATH)/core
EGUI_CODE_SRC		+= $(EGUI_PATH)/widget
EGUI_CODE_SRC		+= $(EGUI_PATH)/font
EGUI_CODE_SRC		+= $(EGUI_PATH)/image
EGUI_CODE_SRC		+= $(EGUI_PATH)/mask
EGUI_CODE_SRC		+= $(EGUI_PATH)/resource
EGUI_CODE_SRC		+= $(EGUI_PATH)/utils
EGUI_CODE_SRC		+= $(EGUI_PATH)/utils/simple_ringbuffer

EGUI_CODE_INCLUDE	+= $(EGUI_PATH)
