#!/usr/bin/env python3
"""Generate HelloSVGSpec C fixture header from SVG source files."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent.parent
APP_DIR = ROOT_DIR / "example" / "HelloSVGSpec"
FIXTURE_DIR = APP_DIR / "fixtures"
MANIFEST_PATH = FIXTURE_DIR / "manifest.json"
OUTPUT_PATH = APP_DIR / "svg_spec_cases_gen.h"


def load_manifest(manifest_path: Path) -> list[dict[str, str]]:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    cases = payload.get("cases", [])
    if not isinstance(cases, list) or not cases:
        raise RuntimeError("fixture manifest does not define any cases")
    return cases


def to_c_string(text: str) -> str:
    return json.dumps(text)


def build_header(cases: list[dict[str, str]], fixture_dir: Path) -> str:
    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/checks/svg_case_codegen.py. */")
    lines.append("#ifndef _SVG_SPEC_CASES_GEN_H_")
    lines.append("#define _SVG_SPEC_CASES_GEN_H_")
    lines.append("")
    lines.append("typedef struct hello_svg_spec_case")
    lines.append("{")
    lines.append("    const char *id;")
    lines.append("    const char *svg_text;")
    lines.append("} hello_svg_spec_case_t;")
    lines.append("")
    lines.append("static const hello_svg_spec_case_t hello_svg_spec_cases[] = {")

    for case in cases:
        fixture_path = fixture_dir / case["file"]
        svg_text = fixture_path.read_text(encoding="utf-8").strip() + "\n"
        lines.append("    {")
        lines.append(f"        {to_c_string(case['id'])},")
        lines.append(f"        {to_c_string(svg_text)},")
        lines.append("    },")

    lines.append("};")
    lines.append("")
    lines.append("#define HELLO_SVG_SPEC_CASE_COUNT ((int)(sizeof(hello_svg_spec_cases) / sizeof(hello_svg_spec_cases[0])))")
    lines.append("")
    lines.append("#endif /* _SVG_SPEC_CASES_GEN_H_ */")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate HelloSVGSpec C fixture header from SVG source files")
    parser.add_argument("--manifest", default=str(MANIFEST_PATH), help="Manifest JSON path")
    parser.add_argument("--fixture-dir", default=str(FIXTURE_DIR), help="Fixture SVG directory")
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Generated header output path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest).resolve()
    fixture_dir = Path(args.fixture_dir).resolve()
    output_path = Path(args.output).resolve()

    cases = load_manifest(manifest_path)
    header = build_header(cases, fixture_dir)
    output_path.write_text(header, encoding="utf-8", newline="\n")
    print(f"Wrote {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
