"""Resource panel -- image/font catalog browser for EmbeddedGUI Designer.

Independent QWidget designed to be placed inside a QDockWidget.
Manages ``resource/src/`` directory and ``resources.xml`` catalog.

Resource directory layout:
    resource/
        src/                 <- source files
            star.png
            test.ttf
            supported_text.txt
        img/                 <- generated by app_resource_generate.py
        font/                <- generated by app_resource_generate.py
        app_egui_resource_generate.h/.c

This panel is a **catalog browser** only -- no per-resource config editors.
Resource configuration (format, alpha, pixelsize, etc.) is managed at the
widget level in the property panel.
"""

import os
import re
import json
import shutil

from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QListWidget,
    QListWidgetItem, QFileDialog, QMessageBox,
    QDialog, QDialogButtonBox, QMenu, QApplication,
    QSplitter, QSizePolicy, QAbstractItemView,
    QInputDialog, QTableWidget, QTableWidgetItem, QHeaderView,
    QComboBox,
)
from PyQt5.QtCore import (
    Qt, QSize, pyqtSignal, QMimeData, QUrl, QTimer, QRect,
)
from PyQt5.QtGui import (
    QPixmap, QIcon, QPixmapCache, QFontDatabase, QFont,
    QPainter, QColor, QDrag, QPen,
)

from qfluentwidgets import (
    PushButton, TabWidget, CaptionLabel,
)

from ..model.resource_catalog import ResourceCatalog, IMAGE_EXTENSIONS, FONT_EXTENSIONS, TEXT_EXTENSIONS
from ..model.string_resource import StringResourceCatalog, DEFAULT_LOCALE


# -- Constants ----------------------------------------------------------

_IMAGE_EXTS = tuple(IMAGE_EXTENSIONS)
_FONT_EXTS = tuple(FONT_EXTENSIONS)
_TEXT_EXTS = tuple(TEXT_EXTENSIONS)

EGUI_RESOURCE_MIME = "application/x-egui-resource"

# Regex for validating English-only filenames
_VALID_FILENAME_RE = re.compile(r'^[A-Za-z0-9_\-]+\.[A-Za-z0-9]+$')


# -- Helpers ------------------------------------------------------------

def _file_size_str(path):
    """Human-readable file size."""
    try:
        size = os.path.getsize(path)
    except OSError:
        return "?"
    if size < 1024:
        return f"{size} B"
    elif size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    else:
        return f"{size / (1024 * 1024):.2f} MB"


def _validate_english_filename(name):
    """Check filename is ASCII letters, digits, underscore, dash, one dot."""
    return bool(_VALID_FILENAME_RE.match(name))


# -- Lazy-loading image list --------------------------------------------

class _LazyImageList(QListWidget):
    """QListWidget that loads thumbnails lazily via QPixmapCache."""

    THUMB_SIZE = 48

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setViewMode(QListWidget.IconMode)
        self.setIconSize(QSize(self.THUMB_SIZE, self.THUMB_SIZE))
        self.setGridSize(QSize(self.THUMB_SIZE + 16, self.THUMB_SIZE + 28))
        self.setResizeMode(QListWidget.Adjust)
        self.setMovement(QListWidget.Static)
        self.setSelectionMode(QAbstractItemView.SingleSelection)
        self.setDragEnabled(True)

        self._load_timer = QTimer(self)
        self._load_timer.setSingleShot(True)
        self._load_timer.setInterval(30)
        self._load_timer.timeout.connect(self._load_visible)

    def showEvent(self, event):
        super().showEvent(event)
        self._schedule_load()

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self._schedule_load()

    def scrollContentsBy(self, dx, dy):
        super().scrollContentsBy(dx, dy)
        self._schedule_load()

    def _schedule_load(self):
        if not self._load_timer.isActive():
            self._load_timer.start()

    def _load_visible(self):
        vr = self.viewport().rect()
        for i in range(self.count()):
            item = self.item(i)
            item_rect = self.visualItemRect(item)
            if not vr.intersects(item_rect):
                continue
            if item.data(Qt.UserRole + 10):
                continue
            path = item.data(Qt.UserRole)
            if not path:
                continue
            self._load_thumb(item, path)

    def _load_thumb(self, item, path):
        try:
            mtime = int(os.path.getmtime(path))
        except OSError:
            mtime = 0
        cache_key = f"egui_thumb:{path}:{mtime}"
        pm = QPixmapCache.find(cache_key)
        if pm is None or pm.isNull():
            pm = QPixmap(path)
            if pm.isNull():
                return
            pm = pm.scaled(self.THUMB_SIZE, self.THUMB_SIZE,
                           Qt.KeepAspectRatio, Qt.SmoothTransformation)
            QPixmapCache.insert(cache_key, pm)
        item.setIcon(QIcon(pm))
        item.setData(Qt.UserRole + 10, True)

    def startDrag(self, supportedActions):
        item = self.currentItem()
        if item is None:
            return
        filename = item.data(Qt.UserRole + 1)  # filename string
        if not filename:
            return
        path = item.data(Qt.UserRole) or ""

        mime = QMimeData()
        data = json.dumps({"type": "image", "filename": filename, "path": path})
        mime.setData(EGUI_RESOURCE_MIME, data.encode("utf-8"))
        mime.setText(filename)

        drag = QDrag(self)
        drag.setMimeData(mime)
        if not item.icon().isNull():
            drag.setPixmap(item.icon().pixmap(32, 32))
        drag.exec_(Qt.CopyAction)


# -- Drag-enabled font list ---------------------------------------------

class _DragFontList(QListWidget):
    """QListWidget for fonts with drag-out support."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setSelectionMode(QAbstractItemView.SingleSelection)
        self.setDragEnabled(True)

    def startDrag(self, supportedActions):
        item = self.currentItem()
        if item is None:
            return
        filename = item.data(Qt.UserRole + 1)  # filename string
        if not filename:
            return
        path = item.data(Qt.UserRole) or ""

        mime = QMimeData()
        data = json.dumps({"type": "font", "filename": filename, "path": path})
        mime.setData(EGUI_RESOURCE_MIME, data.encode("utf-8"))
        mime.setText(filename)

        drag = QDrag(self)
        drag.setMimeData(mime)
        drag.exec_(Qt.CopyAction)


# -- Preview widget ------------------------------------------------------

class _PreviewWidget(QWidget):
    """Bottom preview area -- image large preview or font samples."""

    _SAMPLE_TEXT = "AaBbCc 0123"
    _FONT_SIZES = [12, 16, 24, 32]

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setMinimumHeight(140)
        self._mode = None
        self._pixmap = None
        self._meta_lines = []
        self._font_family = None
        self._font_file = None

    def show_image(self, path):
        self._mode = "image"
        self._font_family = None
        pm = QPixmap(path)
        if pm.isNull():
            self._pixmap = None
            self.update()
            return

        orig_w, orig_h = pm.width(), pm.height()
        fname = os.path.basename(path)
        self._meta_lines = [
            fname,
            f"Size: {orig_w} \u00d7 {orig_h}",
            _file_size_str(path),
        ]

        self._pixmap = pm
        self.update()

    def show_font(self, path, font_family):
        self._mode = "font"
        self._pixmap = None
        self._font_family = font_family
        self._font_file = path
        self._meta_lines = [
            os.path.basename(path),
            font_family or "Unknown family",
            _file_size_str(path),
        ]
        self.update()

    def clear_preview(self):
        self._mode = None
        self._pixmap = None
        self._font_family = None
        self._meta_lines = []
        self.update()

    def paintEvent(self, event):
        if self._mode is None:
            return
        painter = QPainter(self)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.setRenderHint(QPainter.TextAntialiasing)
        w, h = self.width(), self.height()
        if self._mode == "image" and self._pixmap:
            self._paint_image(painter, w, h)
        elif self._mode == "font" and self._font_family:
            self._paint_font(painter, w, h)
        painter.end()

    def _paint_image(self, painter, w, h):
        pm = self._pixmap
        preview_w = max(w - 140, 60)
        preview_h = h - 8
        scaled = pm.scaled(preview_w, preview_h,
                           Qt.KeepAspectRatio, Qt.SmoothTransformation)
        x = 4
        y = (h - scaled.height()) // 2
        painter.drawPixmap(x, y, scaled)
        text_x = x + scaled.width() + 8
        painter.setPen(QColor(200, 200, 200))
        painter.setFont(QFont("Segoe UI", 9))
        fm = painter.fontMetrics()
        ty = 8
        for line in self._meta_lines:
            painter.drawText(text_x, ty + fm.ascent(), line)
            ty += fm.height() + 2

    def _paint_font(self, painter, w, h):
        painter.setPen(QColor(180, 180, 180))
        painter.setFont(QFont("Segoe UI", 8))
        fm = painter.fontMetrics()
        ty = 4
        for line in self._meta_lines:
            painter.drawText(8, ty + fm.ascent(), line)
            ty += fm.height() + 1
        ty += 4
        painter.setPen(QColor(220, 220, 220))
        for sz in self._FONT_SIZES:
            if ty > h - 4:
                break
            font = QFont(self._font_family, sz)
            painter.setFont(font)
            fm2 = painter.fontMetrics()
            painter.drawText(8, ty + fm2.ascent(), f"{sz}px: {self._SAMPLE_TEXT}")
            ty += fm2.height() + 2


# -- Main ResourcePanel --------------------------------------------------

class ResourcePanel(QWidget):
    """Catalog browser for project resources.

    Displays images and fonts from the resource catalog (resources.xml).
    No per-resource configuration -- config is at widget level in property panel.

    Signals:
        resource_selected(str, str): (resource_type, filename)
        resource_imported():         files were imported, refresh needed
    """

    resource_selected = pyqtSignal(str, str)
    resource_imported = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._resource_dir = ""      # .eguiproject/resources/ base directory
        self._src_dir = ""           # same as _resource_dir (fonts/text root)
        self._images_dir = ""        # .eguiproject/resources/images/ subfolder
        self._last_external_import_dir = ""
        self._catalog = ResourceCatalog()
        self._string_catalog = StringResourceCatalog()
        self._font_id_cache = {}
        self._font_family_cache = {}
        self._string_table_updating = False  # guard against cellChanged feedback
        self.setAcceptDrops(True)
        self._init_ui()

    # -- UI construction --

    def _init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(4, 4, 4, 4)
        layout.setSpacing(4)

        splitter = QSplitter(Qt.Vertical)
        splitter.setChildrenCollapsible(False)
        layout.addWidget(splitter, 1)

        # -- Top: Tabs --
        top_widget = QWidget()
        top_layout = QVBoxLayout(top_widget)
        top_layout.setContentsMargins(0, 0, 0, 0)
        top_layout.setSpacing(2)

        self._tabs = TabWidget()

        # Images tab
        img_tab = QWidget()
        img_tab_layout = QVBoxLayout(img_tab)
        img_tab_layout.setContentsMargins(2, 2, 2, 2)
        img_tab_layout.setSpacing(2)

        self._image_list = _LazyImageList()
        self._image_list.itemClicked.connect(self._on_image_clicked)
        self._image_list.itemDoubleClicked.connect(self._on_image_double_clicked)
        self._image_list.setContextMenuPolicy(Qt.CustomContextMenu)
        self._image_list.customContextMenuRequested.connect(
            lambda pos: self._show_context_menu(pos, "image")
        )
        img_tab_layout.addWidget(self._image_list, 1)

        img_btn_layout = QHBoxLayout()
        import_img_btn = PushButton("Import Image...")
        import_img_btn.clicked.connect(self._on_import_image)
        img_btn_layout.addWidget(import_img_btn)
        img_btn_layout.addStretch()
        img_tab_layout.addLayout(img_btn_layout)
        self._tabs.addTab(img_tab, "Images")

        # Fonts tab
        font_tab = QWidget()
        font_tab_layout = QVBoxLayout(font_tab)
        font_tab_layout.setContentsMargins(2, 2, 2, 2)
        font_tab_layout.setSpacing(2)

        self._font_list = _DragFontList()
        self._font_list.itemClicked.connect(self._on_font_clicked)
        self._font_list.itemDoubleClicked.connect(self._on_font_double_clicked)
        self._font_list.setContextMenuPolicy(Qt.CustomContextMenu)
        self._font_list.customContextMenuRequested.connect(
            lambda pos: self._show_context_menu(pos, "font")
        )
        font_tab_layout.addWidget(self._font_list, 1)

        font_btn_layout = QHBoxLayout()
        import_font_btn = PushButton("Import Font...")
        import_font_btn.clicked.connect(self._on_import_font)
        font_btn_layout.addWidget(import_font_btn)

        import_text_btn = PushButton("Import Text...")
        import_text_btn.setToolTip("Import supported-text .txt file into resource/src/")
        import_text_btn.clicked.connect(self._on_import_text)
        font_btn_layout.addWidget(import_text_btn)

        font_btn_layout.addStretch()
        font_tab_layout.addLayout(font_btn_layout)
        self._tabs.addTab(font_tab, "Fonts")

        # Strings (i18n) tab
        strings_tab = QWidget()
        strings_tab_layout = QVBoxLayout(strings_tab)
        strings_tab_layout.setContentsMargins(2, 2, 2, 2)
        strings_tab_layout.setSpacing(2)

        # Locale selector
        locale_row = QHBoxLayout()
        locale_row.addWidget(QLabel("Locale:"))
        self._locale_combo = QComboBox()
        self._locale_combo.setMinimumWidth(80)
        self._locale_combo.currentIndexChanged.connect(self._on_locale_changed)
        locale_row.addWidget(self._locale_combo)
        add_locale_btn = PushButton("Add Locale...")
        add_locale_btn.clicked.connect(self._on_add_locale)
        locale_row.addWidget(add_locale_btn)
        remove_locale_btn = PushButton("Remove Locale")
        remove_locale_btn.clicked.connect(self._on_remove_locale)
        locale_row.addWidget(remove_locale_btn)
        locale_row.addStretch()
        strings_tab_layout.addLayout(locale_row)

        # String table
        self._string_table = QTableWidget()
        self._string_table.setColumnCount(2)
        self._string_table.setHorizontalHeaderLabels(["Key", "Value"])
        self._string_table.horizontalHeader().setStretchLastSection(True)
        self._string_table.horizontalHeader().setSectionResizeMode(
            0, QHeaderView.ResizeToContents
        )
        self._string_table.setSelectionBehavior(QTableWidget.SelectRows)
        self._string_table.setSelectionMode(QTableWidget.SingleSelection)
        self._string_table.cellChanged.connect(self._on_string_cell_changed)
        strings_tab_layout.addWidget(self._string_table, 1)

        # Buttons
        str_btn_layout = QHBoxLayout()
        add_key_btn = PushButton("Add Key...")
        add_key_btn.clicked.connect(self._on_add_string_key)
        str_btn_layout.addWidget(add_key_btn)
        remove_key_btn = PushButton("Remove Key")
        remove_key_btn.clicked.connect(self._on_remove_string_key)
        str_btn_layout.addWidget(remove_key_btn)
        str_btn_layout.addStretch()
        strings_tab_layout.addLayout(str_btn_layout)

        self._tabs.addTab(strings_tab, "Strings")

        top_layout.addWidget(self._tabs, 1)
        splitter.addWidget(top_widget)

        # -- Bottom: Preview area --
        self._preview = _PreviewWidget()
        self._preview.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        splitter.addWidget(self._preview)

        splitter.setStretchFactor(0, 3)
        splitter.setStretchFactor(1, 1)

    # -- Public API --

    def set_resource_dir(self, resource_dir):
        """Set the source directory for resource files and reload.

        The directory should be .eguiproject/resources/ which contains:
          - images/  subfolder for image files
          - font/text files directly
        """
        self._resource_dir = resource_dir or ""
        self._src_dir = resource_dir or ""
        self._images_dir = os.path.join(resource_dir, "images") if resource_dir else ""
        self._image_list.clear()
        self._font_list.clear()
        self._preview.clear_preview()

        if not self._src_dir or not os.path.isdir(self._src_dir):
            self._catalog = ResourceCatalog()
            self._update_tab_titles()
            return

        # Populate image list from catalog (images live in images/ subfolder)
        for fname in self._catalog.images:
            full_path = os.path.join(self._images_dir, fname)
            item = QListWidgetItem(fname)
            item.setData(Qt.UserRole, full_path)
            item.setData(Qt.UserRole + 1, fname)  # filename for drag
            item.setData(Qt.UserRole + 10, False)  # not yet loaded
            exists = os.path.isfile(full_path)
            tooltip = fname
            if not exists:
                tooltip += "\n\u26a0 File not found!"
                item.setForeground(QColor(255, 100, 100))
            item.setToolTip(tooltip)
            self._image_list.addItem(item)

        # Populate font list from catalog
        for fname in self._catalog.fonts:
            full_path = os.path.join(self._src_dir, fname)
            family = self._load_font(full_path) if os.path.isfile(full_path) else ""

            item = QListWidgetItem(fname)
            item.setData(Qt.UserRole, full_path)
            item.setData(Qt.UserRole + 1, fname)  # filename for drag
            tooltip = fname
            if family:
                tooltip += f"\nFamily: {family}"
            if not os.path.isfile(full_path):
                tooltip += "\n\u26a0 File not found!"
                item.setForeground(QColor(255, 100, 100))
            item.setToolTip(tooltip)
            self._font_list.addItem(item)

        self._update_tab_titles()

    def set_resource_catalog(self, catalog):
        """Set the resource catalog and refresh the panel."""
        self._catalog = catalog or ResourceCatalog()
        self.set_resource_dir(self._resource_dir)

    def get_resource_catalog(self):
        """Return the current resource catalog."""
        return self._catalog

    def get_resource_dir(self):
        return self._resource_dir

    def get_src_dir(self):
        return self._src_dir

    def set_string_catalog(self, catalog):
        """Set the i18n string catalog and refresh the Strings tab."""
        self._string_catalog = catalog or StringResourceCatalog()
        self._refresh_string_tab()

    def get_string_catalog(self):
        """Return the current string catalog."""
        return self._string_catalog

    # -- Internal helpers --

    def _update_tab_titles(self):
        n_img = len(self._catalog.images)
        n_font = len(self._catalog.fonts)
        n_str = len(self._string_catalog.all_keys)
        self._tabs.setTabText(0, f"Images ({n_img})")
        self._tabs.setTabText(1, f"Fonts ({n_font})")
        self._tabs.setTabText(2, f"Strings ({n_str})")

    def _load_font(self, path):
        if path in self._font_id_cache:
            return self._font_family_cache.get(path, "")
        fid = QFontDatabase.addApplicationFont(path)
        self._font_id_cache[path] = fid
        if fid >= 0:
            families = QFontDatabase.applicationFontFamilies(fid)
            family = families[0] if families else ""
        else:
            family = ""
        self._font_family_cache[path] = family
        return family

    def _ensure_src_dir(self):
        if not self._resource_dir:
            QMessageBox.warning(self, "Error",
                                "No resource directory configured.\n"
                                "Please save the project first or open an existing project.")
            return False
        self._src_dir = self._resource_dir
        self._images_dir = os.path.join(self._resource_dir, "images")
        os.makedirs(self._src_dir, exist_ok=True)
        os.makedirs(self._images_dir, exist_ok=True)
        return True

    def _default_external_import_dir(self, resource_type=""):
        candidate = self._last_external_import_dir
        if candidate and os.path.isdir(candidate):
            return candidate

        if resource_type == "image" and self._images_dir and os.path.isdir(self._images_dir):
            return self._images_dir

        if self._src_dir and os.path.isdir(self._src_dir):
            return self._src_dir

        return os.path.normpath(os.getcwd())

    def _remember_external_import_paths(self, paths):
        if not paths:
            return
        first_path = paths[0]
        parent_dir = os.path.dirname(first_path)
        if parent_dir and os.path.isdir(parent_dir):
            self._last_external_import_dir = parent_dir

    # -- Selection / double-click --

    def _on_image_clicked(self, item):
        path = item.data(Qt.UserRole)
        filename = item.data(Qt.UserRole + 1)
        if path and os.path.isfile(path):
            self._preview.show_image(path)
        self.resource_selected.emit("image", filename)

    def _on_font_clicked(self, item):
        path = item.data(Qt.UserRole)
        filename = item.data(Qt.UserRole + 1)
        family = self._font_family_cache.get(path, "")
        if path and os.path.isfile(path):
            self._preview.show_font(path, family)
        self.resource_selected.emit("font", filename)

    def _on_image_double_clicked(self, item):
        filename = item.data(Qt.UserRole + 1)
        self.resource_selected.emit("image", filename)

    def _on_font_double_clicked(self, item):
        filename = item.data(Qt.UserRole + 1)
        self.resource_selected.emit("font", filename)

    # -- Import (buttons) --

    def _on_import_image(self):
        if not self._ensure_src_dir():
            return
        paths, _ = QFileDialog.getOpenFileNames(
            self, "Import Images", self._default_external_import_dir("image"),
            "Images (*.png *.bmp *.jpg *.jpeg)"
        )
        if paths:
            self._remember_external_import_paths(paths)
            self._do_import(paths, "image")

    def _on_import_font(self):
        if not self._ensure_src_dir():
            return
        paths, _ = QFileDialog.getOpenFileNames(
            self, "Import Fonts", self._default_external_import_dir("font"),
            "Fonts (*.ttf *.otf)"
        )
        if paths:
            self._remember_external_import_paths(paths)
            self._do_import(paths, "font")

    def _on_import_text(self):
        if not self._ensure_src_dir():
            return
        paths, _ = QFileDialog.getOpenFileNames(
            self, "Import Text Files", self._default_external_import_dir("text"),
            "Text Files (*.txt);;All Files (*.*)"
        )
        if not paths:
            return
        self._remember_external_import_paths(paths)
        for src in paths:
            fname = os.path.basename(src)
            if not _validate_english_filename(fname):
                QMessageBox.warning(
                    self, "Invalid Filename",
                    f"'{fname}' contains non-English characters.\n"
                    "Please rename to use only ASCII letters, digits, "
                    "underscore, and dash."
                )
                continue
            dst = os.path.join(self._src_dir, fname)
            if not os.path.exists(dst):
                shutil.copy2(src, dst)
            self._catalog.add_text_file(fname)
        self.resource_imported.emit()

    def _do_import(self, source_paths, resource_type):
        if not self._ensure_src_dir():
            return
        self._remember_external_import_paths(source_paths)
        imported = 0
        # Choose target directory: images/ for images, root for fonts
        target_dir = self._images_dir if resource_type == "image" else self._src_dir
        for src in source_paths:
            fname = os.path.basename(src)
            # Show rename dialog for each file
            new_name, ok = QInputDialog.getText(
                self, "Rename Resource",
                f"Import '{fname}' as:",
                text=fname,
            )
            if not ok or not new_name:
                continue
            fname = new_name
            if not _validate_english_filename(fname):
                QMessageBox.warning(
                    self, "Invalid Filename",
                    f"'{fname}' is invalid.\n"
                    "Use only ASCII letters, digits, underscore, and dash."
                )
                continue
            dst = os.path.join(target_dir, fname)
            if os.path.exists(dst):
                QMessageBox.warning(self, "Error", f"'{fname}' already exists.")
                continue
            shutil.copy2(src, dst)
            # Add to catalog
            self._catalog.add_file(fname)
            imported += 1
        if imported > 0:
            self.set_resource_dir(self._resource_dir)
            self.resource_imported.emit()

    # -- Drag-drop import from OS --

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():
            for url in event.mimeData().urls():
                path = url.toLocalFile()
                lower = path.lower()
                if lower.endswith(_IMAGE_EXTS + _FONT_EXTS + _TEXT_EXTS):
                    event.acceptProposedAction()
                    return
        event.ignore()

    def dragMoveEvent(self, event):
        if event.mimeData().hasUrls():
            event.acceptProposedAction()
        else:
            event.ignore()

    def dropEvent(self, event):
        if not event.mimeData().hasUrls():
            event.ignore()
            return
        images = []
        fonts = []
        texts = []
        for url in event.mimeData().urls():
            path = url.toLocalFile()
            if not path or not os.path.isfile(path):
                continue
            lower = path.lower()
            if lower.endswith(_IMAGE_EXTS):
                images.append(path)
            elif lower.endswith(_FONT_EXTS):
                fonts.append(path)
            elif lower.endswith(_TEXT_EXTS):
                texts.append(path)

        did_import = False
        if images:
            self._do_import(images, "image")
            did_import = True
        if fonts:
            self._do_import(fonts, "font")
            did_import = True
        if texts and self._ensure_src_dir():
            for src in texts:
                fname = os.path.basename(src)
                if _validate_english_filename(fname):
                    dst = os.path.join(self._src_dir, fname)
                    if not os.path.exists(dst):
                        shutil.copy2(src, dst)
                    self._catalog.add_text_file(fname)
            did_import = True

        if did_import:
            event.acceptProposedAction()
        else:
            event.ignore()

    # -- Right-click context menu --

    def _show_context_menu(self, pos, resource_type):
        if resource_type == "image":
            lst = self._image_list
        else:
            lst = self._font_list

        item = lst.itemAt(pos)
        if item is None:
            return

        filename = item.data(Qt.UserRole + 1)
        path = item.data(Qt.UserRole) or ""

        menu = QMenu(self)

        assign_act = menu.addAction("Assign to Selected Widget")
        assign_act.triggered.connect(lambda: self.resource_selected.emit(resource_type, filename))

        copy_act = menu.addAction(f"Copy: {filename}")
        copy_act.triggered.connect(lambda: QApplication.clipboard().setText(filename))

        menu.addSeparator()

        reveal_act = menu.addAction("Reveal in File Manager")
        reveal_act.triggered.connect(lambda: self._reveal_in_explorer(path))

        menu.addSeparator()

        rename_act = menu.addAction("Rename...")
        rename_act.triggered.connect(lambda: self._rename_resource(filename, resource_type))

        delete_act = menu.addAction("Delete")
        delete_act.triggered.connect(lambda: self._delete_resource(filename, resource_type))

        menu.exec_(lst.viewport().mapToGlobal(pos))

    def _reveal_in_explorer(self, path):
        import subprocess
        import sys as _sys
        if _sys.platform == "win32":
            subprocess.Popen(["explorer", "/select,", os.path.normpath(path)])
        elif _sys.platform == "darwin":
            subprocess.Popen(["open", "-R", path])
        else:
            folder = os.path.dirname(path)
            subprocess.Popen(["xdg-open", folder])

    def _rename_resource(self, old_name, resource_type):
        new_name, ok = QInputDialog.getText(
            self, "Rename Resource", "New filename:", text=old_name
        )
        if not ok or not new_name or new_name == old_name:
            return
        if not _validate_english_filename(new_name):
            QMessageBox.warning(
                self, "Invalid Filename",
                f"'{new_name}' is invalid.\n"
                "Use only ASCII letters, digits, underscore, and dash."
            )
            return
        file_dir = self._images_dir if resource_type == "image" else self._src_dir
        old_path = os.path.join(file_dir, old_name)
        new_path = os.path.join(file_dir, new_name)
        if os.path.exists(new_path):
            QMessageBox.warning(self, "Error", f"'{new_name}' already exists.")
            return
        try:
            if os.path.exists(old_path):
                os.rename(old_path, new_path)
            # Update catalog
            self._catalog.remove_file(old_name)
            self._catalog.add_file(new_name)
            self.set_resource_dir(self._resource_dir)
            self.resource_imported.emit()
        except OSError as e:
            QMessageBox.warning(self, "Error", f"Rename failed: {e}")

    def _delete_resource(self, filename, resource_type):
        reply = QMessageBox.question(
            self, "Delete Resource",
            f"Remove '{filename}' from catalog and delete the file?\n"
            "This cannot be undone.",
            QMessageBox.Yes | QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return
        self._catalog.remove_file(filename)
        file_dir = self._images_dir if resource_type == "image" else self._src_dir
        file_path = os.path.join(file_dir, filename)
        if os.path.isfile(file_path):
            try:
                os.remove(file_path)
            except OSError:
                pass
        self.set_resource_dir(self._resource_dir)
        self.resource_imported.emit()

    # -- Strings tab methods --

    def _refresh_string_tab(self):
        """Refresh locale combo and string table from the catalog."""
        self._string_table_updating = True
        try:
            # Refresh locale combo
            prev_locale = self._get_selected_locale()
            self._locale_combo.blockSignals(True)
            self._locale_combo.clear()
            names = self._string_catalog.locale_display_names
            for locale_code in self._string_catalog.locales:
                display = names.get(locale_code, locale_code or "Default")
                self._locale_combo.addItem(display, locale_code)
            # Restore selection
            idx = self._locale_combo.findData(prev_locale)
            if idx >= 0:
                self._locale_combo.setCurrentIndex(idx)
            self._locale_combo.blockSignals(False)

            self._refresh_string_table()
            self._update_tab_titles()
        finally:
            self._string_table_updating = False

    def _get_selected_locale(self):
        """Get the locale code of the currently selected combo item."""
        idx = self._locale_combo.currentIndex()
        if idx < 0:
            return DEFAULT_LOCALE
        return self._locale_combo.itemData(idx) or DEFAULT_LOCALE

    def _refresh_string_table(self):
        """Repopulate the table for the selected locale."""
        self._string_table_updating = True
        try:
            locale = self._get_selected_locale()
            keys = self._string_catalog.all_keys

            self._string_table.setRowCount(len(keys))
            for row, key in enumerate(keys):
                # Key column (read-only)
                key_item = QTableWidgetItem(key)
                key_item.setFlags(key_item.flags() & ~Qt.ItemIsEditable)
                self._string_table.setItem(row, 0, key_item)

                # Value column (editable)
                value = self._string_catalog.get(key, locale)
                val_item = QTableWidgetItem(value)
                self._string_table.setItem(row, 1, val_item)
        finally:
            self._string_table_updating = False

    def _on_locale_changed(self, index):
        """Locale combo selection changed."""
        if not self._string_table_updating:
            self._refresh_string_table()

    def _on_string_cell_changed(self, row, col):
        """Handle user editing a string value in the table."""
        if self._string_table_updating:
            return
        if col != 1:
            return
        locale = self._get_selected_locale()
        key_item = self._string_table.item(row, 0)
        val_item = self._string_table.item(row, 1)
        if key_item and val_item:
            key = key_item.text()
            value = val_item.text()
            self._string_catalog.set(key, value, locale)
            self.resource_imported.emit()

    def _on_add_string_key(self):
        """Add a new string key to all locales."""
        key, ok = QInputDialog.getText(
            self, "Add String Key",
            "Enter string key name (e.g. app_name):"
        )
        if not ok or not key:
            return
        key = key.strip()

        # Ensure default locale exists
        if DEFAULT_LOCALE not in self._string_catalog.strings:
            self._string_catalog.add_locale(DEFAULT_LOCALE)
            self._refresh_string_tab()

        try:
            self._string_catalog.add_key(key, "")
        except ValueError as e:
            QMessageBox.warning(self, "Invalid Key", str(e))
            return

        self._refresh_string_tab()
        self.resource_imported.emit()

    def _on_remove_string_key(self):
        """Remove the selected string key from all locales."""
        row = self._string_table.currentRow()
        if row < 0:
            return
        key_item = self._string_table.item(row, 0)
        if not key_item:
            return
        key = key_item.text()
        reply = QMessageBox.question(
            self, "Remove String Key",
            f"Remove key '{key}' from all locales?",
            QMessageBox.Yes | QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return
        self._string_catalog.remove_key(key)
        self._refresh_string_tab()
        self.resource_imported.emit()

    def _on_add_locale(self):
        """Add a new locale (e.g. 'zh', 'ja', 'fr')."""
        locale, ok = QInputDialog.getText(
            self, "Add Locale",
            "Enter locale code (e.g. zh, ja, fr, de):"
        )
        if not ok or not locale:
            return
        locale = locale.strip().lower()
        if not locale:
            return

        # Ensure default locale exists first
        if DEFAULT_LOCALE not in self._string_catalog.strings:
            self._string_catalog.add_locale(DEFAULT_LOCALE)

        self._string_catalog.add_locale(locale)
        self._refresh_string_tab()

        # Select the new locale
        idx = self._locale_combo.findData(locale)
        if idx >= 0:
            self._locale_combo.setCurrentIndex(idx)

        self.resource_imported.emit()

    def _on_remove_locale(self):
        """Remove the currently selected locale."""
        locale = self._get_selected_locale()
        if locale == DEFAULT_LOCALE:
            QMessageBox.information(
                self, "Cannot Remove",
                "The default locale cannot be removed."
            )
            return
        reply = QMessageBox.question(
            self, "Remove Locale",
            f"Remove locale '{locale}' and all its translations?",
            QMessageBox.Yes | QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return
        self._string_catalog.remove_locale(locale)
        self._refresh_string_tab()
        self.resource_imported.emit()
