

#ifndef _APP_EGUI_RESOURCE_GENERATE_H_
#define _APP_EGUI_RESOURCE_GENERATE_H_

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

#include "egui.h"

extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0001_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0002_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0003_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0004_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0005_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0006_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0007_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0008_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0009_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0010_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0011_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0012_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0013_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0014_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0015_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0016_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0017_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0018_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0019_qoi_rgb565_0;
extern const egui_image_qoi_t egui_res_image_cmp_qoi_frame_test_0020_qoi_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0001_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0002_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0003_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0004_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0005_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0006_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0007_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0008_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0009_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0010_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0011_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0012_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0013_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0014_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0015_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0016_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0017_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0018_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0019_rle_rgb565_0;
extern const egui_image_rle_t egui_res_image_cmp_rle_frame_test_0020_rle_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0001_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0002_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0003_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0004_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0005_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0006_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0007_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0008_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0009_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0010_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0011_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0012_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0013_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0014_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0015_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0016_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0017_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0018_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0019_rgb565_0;
extern const egui_image_std_t egui_res_image_cmp_std_frame_test_0020_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0001_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0002_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0003_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0004_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0005_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0006_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0007_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0008_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0009_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0010_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0011_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0012_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0013_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0014_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0015_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0016_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0017_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0018_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0019_rgb565_0;
extern const egui_image_std_t egui_res_image_test_std_frame_test_0020_rgb565_0;


enum {
EGUI_EXT_RES_ID_BASE = 0x00, // avoid conflict with NULL.

EGUI_EXT_RES_ID_MAX,
};

extern const uint32_t egui_ext_res_id_map[EGUI_EXT_RES_ID_MAX];

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_RESOURCE_GENERATE_H_ */

