

#ifndef _APP_EGUI_RESOURCE_GENERATE_H_
#define _APP_EGUI_RESOURCE_GENERATE_H_

/* Set up for C function definitions, even when using C++ */
#ifdef __cplusplus
extern "C" {
#endif

#include "egui.h"

extern const egui_image_std_t egui_res_image_test_frame_test_0001_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0002_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0003_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0004_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0005_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0006_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0007_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0008_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0009_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0010_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0011_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0012_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0013_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0014_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0015_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0016_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0017_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0018_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0019_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0020_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0021_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0022_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0023_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0024_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0025_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0026_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0027_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0028_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0029_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0030_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0031_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0032_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0033_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0034_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0035_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0036_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0037_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0038_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0039_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0040_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0041_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0042_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0043_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0044_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0045_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0046_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0047_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0048_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0049_rgb565_0;
extern const egui_image_std_t egui_res_image_test_frame_test_0050_rgb565_0;


enum {
EGUI_EXT_RES_ID_BASE = 0x00, // avoid conflict with NULL.

EGUI_EXT_RES_ID_MAX,
};

extern const uint32_t egui_ext_res_id_map[EGUI_EXT_RES_ID_MAX];

/* Ends C function definitions when using C++ */
#ifdef __cplusplus
}
#endif

#endif /* _APP_EGUI_RESOURCE_GENERATE_H_ */

