name: Compile Check
run-name: ${{ github.actor }} is start compile check 🚀
on: [push]
jobs:
  env_and_compile_check:
    #runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup C/C++ env
        uses: rlalik/setup-cpp-compiler@v1.2
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Start Compile Test, full compile check.
        run: python scripts\code_compile_check.py --full-check
      - run: echo "🍏 This job's status is ${{ job.status }}."
